export const manufacturerModels: Record<string, string[]> = {
  'Adria': ['Astella', 'Alpina', 'Adora', 'Altea', 'Action', 'Aviva', 'Aviva Lite', 'Supersonic', 'Sonic', 'Matrix', 'Coral', 'Coral XL', 'Compact Max', 'Compact', 'Supertwin', 'Twin Sports', 'Twin Supreme', 'Twin'],
  'Affinity': ['One', 'Duo', 'Three', 'Four', 'Five', 'M Duo', 'M Three', 'M Four', 'Freedo'],
  'Ahorn': ['Van', 'Camp', 'Canada', 'Alaska'],
  'Arca': ['America', 'Europa', 'A-Series', 'T-Series', 'Superamerica', 'M-Series', 'P-Series', 'Junior'],
  'Autostar': ['Prestige', 'Performance', 'Passion', 'Celtic Edition', 'Privilege', 'Auros', 'Athenor', 'Aryal', 'Axea', 'Atlas', 'MobilStar', 'Van', '30e Edition'],
  'Autotrail': ['Adventure', 'Excel', 'Expedition', 'Expedition Coachbuilt', 'F-Line', 'Frontier', 'Grande Frontier', 'Imala', 'Tracker', 'V-Line'],
  'Bailey': ['Autograph', 'Adamo', 'Alora', 'Alicanto Grande Deluxe', 'Pegasus Black', 'Phoenix Black', 'Unicorn Deluxe', 'Discovery'],
  'Bavaria-Camp': ['Vancentro', 'Vertigo', 'Variego', 'Ducato', 'Sol y Sombra', 'Player', 'Primeur', 'Vanverto', 'Vaniano', 'Tren-D', 'Unik', 'T 726', 'V 540G', 'i720'],
  'Bela': ['DBS 485', 'Bonair 593', 'Van 600 DB', 'DB600 Compact', 'Easy Barbados', 'Trendy'],
  'Benimar': ['Benivan', 'Tessoro', 'Mileo', 'Sport', 'Amphitryon', 'Yrteo'],
  'Bimobil': ['BJ 383', 'EX 358', 'EX 366', 'EX 368', 'EX 412 SH', 'EX 420', 'EX 432', 'EX 462', 'EX 480', 'EX 510', 'HD 420', 'HD 435', 'HR 380', 'husky 230', 'husky 240', 'husky 270', 'LB 365', 'LBX 365', 'LHX 428', 'ST 702'],
  'Bravia': ['Swan 495', 'Swan 599', 'Swan 636', 'Swan 680'],
  'Burow': ['Oman', 'BIG5', 'Capron', 'Liberte'],
  'Bürstner': ['Signature', 'Papillon', 'Habiton', 'Lyseo', 'Lineo', 'Campeo', 'Eliseo', 'Copa', 'Playa', 'Premio', 'Premio Plus', 'Averso', 'Averso Plus', 'Belcanto', 'Amara', 'Flipper', 'Nexxo', 'Delfin'],
  'CI International': ['Horon', 'Magis', 'Mizar', 'Riviera', 'Sinfonia', 'X-Til', 'Carioca', 'Elliot', 'Esperia', 'Kyros', 'S-Range', 'Litoranea', 'Onice'],
  'CS Reisemobile': ['CORONA', 'COSMO', 'DUO', 'DUO INDEPENDENT', 'ENCANTO', 'INDEPENDENT', 'LUXOR', 'RONDO', 'Amigo'],
  'Campster': ['Campster', 'Campstar', 'Vanster', 'e-Vanster'],
  'Carado': ['Camper Vans', 'Vans', 'Teilintegrierte', 'Integrierte', 'Alkoven'],
  'Carthago': ['c-tourer', 'chic c-line', 'chic e-line', 'chic s-plus', 'liner-for-two', 'c-compactline', 'highliner'],
  'Challenger': ['Vans', 'Teilintegrierte', 'Vollintegrierte', 'X-Modelle', 'Teilintegrierte S', 'Alkoven'],
  'Chateau': ['Calista', 'La Car', 'Chiara', 'Caratt', 'Cantara'],
  'Chausson': ['Vans', 'S-Teilintegrierte', 'X', 'Teilintegrierte', 'Alkoven', 'Vollintegrierte'],
  'Clever': ['Tour 540', 'Celebration 600', 'Spirit 600', 'Vario Kids 600', 'Runner 636', 'Runner 636 Active', 'Aventuro 600', 'Drive 540', 'Drive 600', 'Duo 540', 'Cleverly'],
  'Concorde': ['Credo', 'Carver', 'Charisma', 'Cruiser', 'Liner', 'Centurion'],
  'Crosscamp': ['ADVTR', 'EXPLR', 'EXPDN'],
  'Dethleffs': ['Globebus', 'c-joy', 'c-go', 'XL Family', 'Just Go', 'Trend', 'Esprit', 'Alpa', 'Summer Edition', 'Camper', 'Aero', 'Beduin', 'Nomad', 'Advantage', 'Globetrotter'],
  'Dreamer': ['D68', 'D43 UP', 'D55', 'D55 UP', 'CAMPER SPORT', 'CAMPER FIVE', 'D43 SELECT', 'D43 UP SELECT', 'CITY CAMP SELECT', 'CAP LAND SELECT', 'D55 SELECT', 'D68 SELECT', 'D68 UP SELECT', 'D62 SELECT', 'LIVING VAN SELECT', 'FAMILY VAN SELECT', 'CAMPER VAN XL SELECT'],
  'Eifelland': ['Holiday', 'Deseo', 'Sunshine', 'Relax', 'Businesscamper', 'Workcation', 'Eifelland Classic', 'HD Camper'],
  'Elnagh': ['Magnum', 'E-Van', 'T-Loft', 'Baron', 'Clipper', 'Columbia', 'Cutter', 'Dinghy', 'Doral', 'Duke', 'Marlin'],
  'Etrusco': ['CV-Modell Fiat', 'CV-Modell Plus', 'V-Modell Ford', 'T-Modell Fiat', 'T-Modell Base', 'A-Modell Base', 'I-Modell Fiat'],
  'Eura Mobil': ['Vans', 'Activa One', 'Profila T', 'Profila RS', 'Contura', 'Xtura', 'Integra Line', 'Integra'],
  'Fendt': ['Apero', 'Bianco', 'Tendenza', 'Diamant', 'Saphir'],
  'Fleurette': ['Baxter', 'Mayflower', 'Wincester', 'Migrateur', 'Magister', 'Discover'],
  'Ford': ['Nugget', 'Transit', 'Econoline'],
  'Forster': ['Alkoven', 'Teilintegrierte', 'Integrierte', 'Vans', 'Livin Up', 'Vibe'],
  'Frankia': ['PLATIN', 'TITAN', 'NOCTRA Cruiser', 'F-Line', 'TOGETHER', 'NEO', 'NOW', 'FINAL EDITION', 'Comfort Class', 'ExclusiveClass', 'Holiday Class', 'Luxury Class'],
  'GiottiLine': ['Siena', 'Toscan', 'GiottiCompact', 'GiottiVan'],
  'Globe-Traveller': ['Explorer', 'Voyager', 'Falcon', 'Pathfinder'],
  'Globecar': ['Roadscout', 'Globestar', 'Campscout', 'Roadstar', 'Summit', 'Summit Prime', 'Summit Shine', 'Globescout'],
  'Glücksmobil': ['A', 'C', 'S', 'T', 'VAN'],
  'HRZ': ['Tango', 'Mambo', 'Life', 'Chamäleon', 'Beach', 'Joy', 'Dream', 'Star', 'Family L', 'Toscana', 'Biker', 'Freedom', 'Sahara', 'Casablanca', 'Safari', 'Casablanca L', 'Casablanca U', 'Racing', 'Longus', 'Reha Camper 2'],
  'Hobby': ['PRESTIGE T', 'MAXIA T', 'ONTOUR C', 'ONTOUR T', 'ONTOUR A', 'ONTOUR', 'DE LUXE', 'EXCELLENT', 'EXCELLENT EDITION', 'PRESTIGE', 'MAXIA', 'BEACHY'],
  'Hymer': ['B-Klasse', 'Exsis', 'ML-T', 'Venture S', 'Grand Canyon S', 'GT-S', 'Redwood', 'Eriba Touring', 'Eriba Feeling', 'Eriba Nova', 'Hymercar', 'Hymermobil', 'Hymer Van', 'Hymer Tramp', 'Nova', 'Feeling'],
  'Ilusion': ['I.Lux', 'XMK', 'Premium'],
  'Itineo': ['PS740', 'PF600', 'PC640', 'PJ700', 'PM740', 'CM660', 'CJ660', 'JC740', 'SB740', 'MB740', 'FC650', 'MC740'],
  'Joa Camp': ['60F', '75T', '75Q', '70T', '70Q', '54G', '60G', '63T'],
  'Joint': ['Spaceline', 'E-Serie', 'J-Serie', 'S-Serie', 'T-Serie', 'X-Serie', 'Z-Serie', 'New Life', 'Elegance'],
  'Kabe': ['Imperial', 'Crown', 'Royal', 'Novum', 'Classic', 'Travel Master', 'Van', 'Edelstein', 'Ametist', 'Smaragd', 'Safir', 'Rubin', 'Onyx', 'Briljant', 'Hacienda'],
  'Karmann': ['Davis', 'Dexter', 'Duncan', 'Davis Lifestyle', 'Davis Trendstyle'],
  'Knaus': ['VAN TI', 'VAN TI PLUS', 'L!VE TI', 'SKY TI', 'L!VE WAVE', 'L!VE I', 'SUN I', 'SPORT&FUN', 'YASEO', 'SPORT', 'SÜDWIND', 'BOXLIFE', 'BOXTIME'],
  'LMC': ['Tracer', 'Tourer', 'Cruiser', 'Innovan', 'Breezer', 'Sassino', 'Style', 'Style Lift', 'Vivo', 'Musica', 'Exquisite VIP', 'e:dero', 'Videro', 'Tandero', 'Luxus'],
  'La Strada': ['NOVA', 'REGENT', 'AVANTI'],
  'Laika': ['Ecovip', 'Kreos', 'Kosmo', 'Rexosline', 'X'],
  'Le Voyageur': ['Eterna', 'Héritage', 'LV', 'Liner'],
  'Malibu': ['Van', 'Integrierte', 'Teilintegrierte', 'relax', 'genius', 'first class - two rooms', 'diversity', 'comfort', 'compact'],
  'McLouis': ['Glamys', 'Mc4', 'Nevis', 'Menfys', 'Lagan', 'Steel', 'Tandy', 'Glen'],
  'MegaMobil': ['Mega Lounge', 'Mega Classic', 'Mega Re-Aktiv', 'Mega Sport', 'Mega Revolution', '4x4 Camper'],
  'Mercedes-Benz': ['Marco Polo', 'T-Klasse', 'V-Klasse', 'Sprinter', 'Vito', 'Citan'],
  'Miller': ['Ontario', 'Winnipeg', 'Erie', 'Toronto', 'M-Liner', 'Maryland', 'Alaska', 'Montana', 'Michigan', 'Ohio', 'New York', 'Louisiana', 'Colorado'],
  'Mobilvetta': ['Admiral', 'Krosser', 'Kea P', 'Kea I', 'K-Yacht Tekno Line', 'Kea Kompakt', 'K-Silver'],
  'Mooveo': ['Van', 'Teilintegriert', 'Vollintegriert', 'Alkoven'],
  'Morelo': ['Home', 'Loft', 'Loft Liner', 'Loft Premium', 'Loft Premium Liner', 'Palace', 'Palace Liner', 'Palace Liner S-Way', 'Empire Liner', 'Grand Empire'],
  'Niesmann+Bischoff': ['iSmove', 'Arto', 'Flair', 'Clou'],
  'NobelART': ['T-5000', 'T-6000', 'T-7000', 'A-7000', 'A-9000', 'Liner'],
  'Notin': ['Progress', 'Excel', 'NotinLiner', 'Bilbao', 'Lorca', 'Lindau', 'Avila', 'Bruges', 'Vera', 'Rubi', 'Calvia'],
  'Orangecamp': ['T-Serie', 'A-Serie', 'K-Serie', 'Crafter'],
  'P.L.A.': ['M Klasse', 'S Klasse', 'Siena', 'GiottiVAN', 'GiottiCompact'],
  'Panama': ['P09', 'P10+', 'P12+', 'P10H', 'Urban 11', 'Peak P10+'],
  'Phoenix': ['Maxi', 'Midi', 'Top-Alkoven', 'Top-Liner', 'Maxi-Liner', 'TopX-Alkoven'],
  'Pilote': ['Pacific', 'Galaxy', 'Atlas', 'V-Baureihe', 'Évidence'],
  'Pössl': ['D-Line', 'H-Line', 'Summit', 'X-Line', 'Vanline', 'Trenta', 'Campster', 'Vanster', 'Roadstar', 'Roadcruiser', '2Win', 'Concorde Compact'],
  'Randger': ['R490', 'R499', 'R530', 'R535', 'R540', 'R550', 'R555', 'R560', 'R570', 'R602', 'R640'],
  'Rapido': ['V-Serie', 'C-Serie', 'Serie 6', 'Serie 8', 'Serie 80dF', 'Serie M', 'Serie i', 'Distinction', '80dF', '6F', '8F', 'M', 'C', 'i', 'V', '6', '8'],
  'Reimo': ['Trio High Style', 'Triostyle', 'City Van', 'Camp', 'Camp Maxi', 'EQV'],
  'Rimor': ['Horus', 'Kilig', 'Sarus', 'Super Brig', 'Sailer', 'Seal', 'Katamarano', 'Rimor Van'],
  'Roadcar': ['R 540', 'R 600', 'R 601', 'R 640'],
  'Robeta': ['Ares', 'Helios', 'Kronos', 'Apollo', 'Adonis', 'Womondo', 'Air'],
  'Roller Team': ['Kronos', 'Zefiro', 'Livingstone', 'Atessa', 'T-Line', 'Auto-Roller', 'Pegaso'],
  'SEA': ['Sharky', 'Gigant', 'A 610', 'Dart', 'Extreme 369', 'Sloop'],
  'Soma Camp': ['SOMA VAN', 'T680 EB', 'T700 EB', 'T 650 EB', 'L-LINE', 'Comfort 530 E', 'Family 560 FMK', 'Doogi 560 FMK'],
  'Sun Living': ['Lido', 'A-Serie', 'C-Serie', 'S-Serie', 'V-Serie'],
  'Sunlight': ['Cliff', 'Cliff Adventure', 'Vanlife', 'Cliff X', 'Cliff 4x4', 'Cliff 4x4 Greentrek', 'Vans', 'Vans Adventure', 'Teilintegrierte', 'Teilintegrierte Adventure', 'Teilintegrierte Ford Adventure', 'Integrierte Adventure', 'Alkoven', 'C-Klasse'],
  'TEC': ['Freetec', 'Rotec', 'I-TEC', 'AdvanTec', 'Travel King', 'Tour live', 'Weltbummler', 'Travelbird'],
  'Tabbert': ['ROSSINI', 'DA VINCI', 'PEP', 'VIVALDI', 'PUCCINI', 'CELLINI', 'PANTIGA', 'CAZADORA', 'SENARA'],
  'Tourne': ['Select', 'Cruise'],
  'Trigano': ['Mini Freestyle', 'Rubis', 'Galleon', 'Silver'],
  'VANTourer': ['540 D', '600 D', '600 L', '630 L', 'Urban'],
  'VARIO mobil': ['VARIO Star', 'VARIO Perfect', 'VARIO Alkoven', 'VARIO Signature'],
  'Volkswagen': ['California', 'Grand California', 'Caddy California', 'ID. Buzz', 'Transporter', 'Crafter', 'Multivan', 'Caravelle', 'Vanagon', 'Eurovan'],
  'Weinsberg': ['CaraCompact', 'CaraSuite', 'CaraHome', 'CaraCore', 'CaraLoft', 'CaraBus', 'CaraTour', 'X-Cursion CUV', 'X-Cursion VAN', 'X-Pedition', 'CaraOne', 'CaraCito'],
  'Westfalia': ['Club Joker', 'Kepler', 'Jules Verne', 'Kelsey', 'Kipling', 'Columbus', 'Sven Hedin', 'James Cook', 'Wave', 'Joker'],
  'Wilk': ['Deluxe', 'Sento', 'Vida', 'Eterno', 'Safari', 'S3', 'S4', 'De Luxe', 'Stern', 'Sport'],
  'Wingamm': ['Oasi 540', 'Oasi 610', 'Oasi 690', 'Brownie', 'Rookie', 'City Pro'],
  'XGO': ['XVAN', 'XCAMP', 'DYNAMIC'],
  'Yucon': ['K-peak', '6.0 GD', '6.0 BD', 'V-city', '7.0 GD'],
  'Andere': ['Sonstiges Modell']
};

// Sorted manufacturer list
export const popularManufacturers = Object.keys(manufacturerModels).sort();

// Body type options matching the motorhome_body_type enum
export const bodyTypes = [
  'Teilintegriert',
  'Alkoven',
  'Vollintegriert',
  'Kastenwagen',
  'Campingbus',
] as const;

// Vehicle type options
export const vehicleTypes = [
  { value: 'Wohnmobil', label: 'Wohnmobil' },
  { value: 'Wohnwagen', label: 'Wohnwagen' },
] as const;
