export const manufacturerModels: Record<string, string[]> = {
  'Adria': ['Astella', 'Alpina', 'Adora', 'Altea', 'Action', 'Aviva', 'Aviva Lite', 'Adiva', 'Supersonic', 'Sonic', 'Sonic Plus', 'Sonic Supreme', 'Sonic Axess', 'Matrix', 'Matrix Plus', 'Matrix Supreme', 'Matrix Axess', 'Matrix Axess 650 SF', 'Matrix Axess 670 SL', 'Coral', 'Coral XL', 'Coral Supreme', 'Coral Axess', 'Coral Sport', 'Coral 590 DS', '640 SL', '640 SL Axess', '670 SL Axess', '690 SC Axess', 'Compact Max', 'Compact', 'Compact Plus', 'Compact Supreme', 'Compact Axess', 'Compact SL', 'Compact SP', 'Supertwin', 'Twin Sports', 'Twin Supreme', 'Twin', 'Twin Plus', 'Twin Plus 600 SP', 'Twin Plus 640 SLB', 'Twin Axess', 'Izola', 'Adriatik', 'Vision', 'Sun Living'],
  'Affinity': ['One', 'Duo', 'Three', 'Four', 'Five', 'M Duo', 'M Three', 'M Four', 'Freedo'],
  'Ahorn': ['Van', 'Van City', 'Camp', 'Camp T', 'Camp A', 'Canada', 'Canada T', 'Canada TE', 'Canada TE plus', 'Canada AD', 'Alaska', 'Alaska TE', 'Alaska TQ', 'ACT', 'ACT 590', 'EC 660', 'A 595', 'A 690', 'T 640 plus', 'T 690 plus', 'C-Klasse', 'Van Big City', 'Eco Van'],
  'Ahorn Camp': ['Canada TE plus', 'Canada T', 'Alaska TE', 'Van City', 'Camp T', 'A 690', 'A 595'],
  'Arca': ['America', 'Europa', 'A-Series', 'T-Series', 'Superamerica', 'M-Series', 'P-Series', 'Junior', 'Europa New Deal', 'America New Deal', 'America Compact'],
  'Autostar': ['Prestige', 'Performance', 'Passion', 'Celtic Edition', 'Privilege', 'Auros', 'Athenor', 'Aryal', 'Axea', 'Atlas', 'MobilStar', 'Van', '30e Edition', 'Premice'],
  'Autotrail': ['Adventure', 'Excel', 'Expedition', 'Expedition Coachbuilt', 'F-Line', 'Frontier', 'Grande Frontier', 'Imala', 'Tracker', 'V-Line', 'V-Line SE', 'V-Line Sport', 'Expedition Van'],
  'Bailey': ['Autograph', 'Adamo', 'Alora', 'Alicanto Grande Deluxe', 'Pegasus Black', 'Phoenix Black', 'Unicorn Deluxe', 'Discovery', 'Endeavour', 'Endurance'],
  'Bavaria-Camp': ['Vancentro', 'Vertigo', 'Variego', 'Ducato', 'Sol y Sombra', 'Player', 'Primeur', 'Vanverto', 'Vaniano', 'Tren-D', 'Unik', 'T 726', 'V 540G', 'i720', 'Qwest', 'Kompakt', 'Intense', 'Nomade'],
  'Bela': ['DBS 485', 'Bonair 593', 'Van 600 DB', 'DB600 Compact', 'Easy Barbados', 'Trendy', 'P69', 'P76', 'Macau Easy', 'Easy Mauritius', 'Hawaii Easy'],
  'Benimar': ['Benivan', 'Tessoro', 'Mileo', 'Sport', 'Amphitryon', 'Yrteo', 'Perseo', 'Cocoon'],
  'Bimobil': ['BJ 383', 'EX 358', 'EX 366', 'EX 368', 'EX 412 SH', 'EX 420', 'EX 432', 'EX 462', 'EX 480', 'EX 510', 'HD 420', 'HD 435', 'HR 380', 'husky 230', 'husky 240', 'husky 270', 'LB 365', 'LBX 365', 'LHX 428', 'ST 702'],
  'Bravia': ['Swan 495', 'Swan 599', 'Swan 636', 'Swan 680'],
  'Bresler Mobile': ['Junior', 'Junior Exclusiv', 'Junior DK', 'Junior DK-F', 'Junior DK-G', 'Horizont', 'Horizont DF', 'Horizont U', 'Action Exclusiv', 'Bresler 694'],
  'Burow': ['Oman', 'BIG5', 'Capron', 'Liberte', 'Trek5', 'VIP'],
  'Bürstner': ['Signature SFT', 'Signature', 'Habiton HM', 'Habiton HMX', 'Habiton', 'Papillon', 'Lyseo Gallery', 'Lyseo Harmony', 'Lyseo M', 'Lyseo TD', 'Lyseo T', 'Lyseo T 700', 'Lyseo T 736', 'Lyseo T 744', 'Lyseo TD 744', 'Lyseo TD 736', 'Lyseo Time', 'Lyseo Time SkyLine', 'Lyseo IT', 'Lyseo I', 'Lyseo A', 'Lineo C', 'Lineo T', 'Campeo C', 'Campeo TD', 'Campeo', 'Eliseo C', 'Eliseo T', 'Eliseo', 'Travel Van', 'Ixeo', 'Ixeo Time', 'Ixeo Plus', 'City Car', 'Copa', 'Playa', 'Premio', 'Premio Plus', 'Premio Life', 'Averso', 'Averso Plus', 'Averso Harmony', 'Belcanto', 'Amara', 'Flipper', 'Nexxo', 'Nexxo Van', 'Nexxo Time', 'Delfin', 'Limited', 'Limited G 727', 'Active', 'Black Forest Edition', 'Elegance', 'A 535', 'A 535 Active', 'A 547 Limited', 'A 574', 'A 574/3', 'A 660', 'A 700', 'T 620', 'T 700', 'T 727', 'T 728', 'T 736', 'T 744', 'I 690', 'I 720', 'I 736', 'Argos', 'Solano', 'Marano', 'Brevio', 'Aviano'],
  'CI International': ['Horon', 'Magis', 'Mizar', 'Riviera', 'Sinfonia', 'X-Til', 'Carioca', 'Elliot', 'Esperia', 'Kyros', 'S-Range', 'Litoranea', 'Onice', 'Horon Fit', 'Spring Edition', 'Magis Elite Selekt', 'Kyros Go', 'Kyros Elite'],
  'CS Reisemobile': ['CORONA', 'COSMO', 'DUO', 'DUO INDEPENDENT', 'ENCANTO', 'INDEPENDENT', 'LUXOR', 'RONDO', 'Rondo XL', 'Amigo'],
  'Campster': ['Campster', 'Campstar', 'Vanster', 'e-Vanster', 'Vanstar'],
  'Carado': ['CV 540', 'CV 541', 'CV 600', 'CV 601', 'CV 640', 'T 135', 'T 328', 'T 337', 'T 338', 'T 339', 'T 347', 'T 348', 'T 447', 'T 448', 'T 449', 'T 459', 'V 132', 'V 337', 'V 339', 'V 347', 'V 449', 'V 600', 'I 338', 'I 339', 'I 447', 'I 449', 'I 459', 'A 361', 'A 449', 'A 461', 'A 464', 'A 484', 'Capron', 'VLOW', 'Edition 15', 'Edition 17', 'Edition 19', 'Touch'],
  'Carthago': ['c-tourer', 'c-tourer T', 'c-tourer I', 'c-tourer T 4.9 LE', 'c-tourer T 4.9 LEL', 'c-tourer T 5.0 LE', 'c-tourer T 5.0 LEL', 'c-tourer I 4.9 LE', 'c-tourer I 5.0 LE', 'c-compactline', 'c-compactline T', 'c-compactline I', 'c-compactline T 4.9 LE', 'c-compactline I 4.9 LE', 'c-compactline I 4.9 LE V', 'chic c-line', 'chic c-line T', 'chic c-line I', 'chic c-line XL', 'chic c-line I 4.9 LE', 'chic c-line I 4.9 LEL', 'chic c-line I 5.2 LE', 'chic e-line', 'chic e-line I', 'chic e-line I 50', 'chic e-line I 51', 'chic e-line I 58', 'chic e-line I 61', 'chic e-line I 64', 'chic e-line I 65', 'chic e-line T', 'chic s-plus', 'chic s-plus I', 'chic s-plus I 50', 'chic s-plus I 51', 'chic s-plus I 58', 'chic s-plus I 61', 'e-line', 'e-line I', 'liner-for-two', 'liner-for-two I', 'highliner', 'c-tourer Edition+', 'malibu I', 'malibu T'],
  'Challenger': ['V 114', 'V 217', 'X 150', 'X 250', 'S 194', 'S 264', 'C 256', 'C 264', 'C 394', 'A 264', 'Graphite Edition'],
  'Chateau': ['Calista', 'La Car', 'Chiara', 'Caratt', 'Cantara'],
  'Chausson': ['V 594', 'V 697', 'S 514', 'S 697', 'X 550', 'X 650', 'C 514', 'C 594', 'C 627', 'C 630 Etape Line', 'C 640', 'C 656', 'C 697', 'C 717', 'C 787', 'C 788', 'Welcome 64', 'Welcome 510', 'Welcome 620', 'Welcome 717', '650', '660', '720', '757', '788', 'BXL', 'Titanium', 'First Line', 'Flash', 'Welcome', 'Twist', 'VIP', 'Special Edition', 'Sport Line', 'Odyssee'],
  'Clever': ['Tour 540', 'Celebration 600', 'Spirit 600', 'Vario Kids 600', 'Runner 636', 'Runner 636 Active', 'Aventuro 600', 'Drive 540', 'Drive 600', 'Duo 540', 'Cleverly', 'Drive 600 Kids', 'Sunny', 'Vandeo Beach', 'Roadrider', 'Roadrider 540', 'Roadrider 600', 'Mover'],
  'Concorde': ['Credo', 'Credo Action', 'Credo Action 690 SP', 'Credo 690 SP', 'Credo 791 G', 'Credo Edition', 'Carver', 'Carver 720 ST', 'Carver 791 G', 'Carver 891 L', 'Charisma', 'Charisma III', 'Cruiser', 'Cruiser Daily', 'Cruiser 890 L', 'Cruiser 990 G', 'Liner', 'Liner Plus', 'Liner 1090 G', 'Centurion', 'Compact', 'Carver Diamond', 'Cruiser Atego', 'Centurion Actros', 'Carver Select'],
  'Crosscamp': ['ADVTR', 'EXPLR', 'EXPDN', 'FLEX', 'LITE', 'FULL'],
  'Dethleffs': ['Globebus', 'Globebus GO', 'Globebus Camp', 'Globebus Performance', 'Globebus Performance 4x4', 'Globetrotter XL I', 'Globetrotter XXL A', 'Globetrail', 'Globetrail 600 Advantage DR', 'Globetrail VW', 'Globeline', 'Globeline T 6613 EB', 'Globevan', 'Globevan e.Hybrid', 'Just Camp', 'Just Go', 'Trend', 'Trend T', 'Trend T 6613 EB', 'Trend T 7057 EB', 'Trend I', 'Trend A', 'Trend 90', 'Esprit', 'Esprit I', 'Esprit Comfort', 'Alpa', 'Alpa A', 'Alpa A 7820-2', 'A 7820-2', 'Yoka Go', 'XL Family', 'c-joy', 'c-go', 'c-go Up', 'c-go XL Family', 'Summer Edition', 'Pulse', 'Pulse Classic', 'Pulse Gold', 'Camper', 'Camper LiveStyle 560', 'Camper Lifestyle', 'Aero', 'Beduin', 'Beduin Scandinavia', 'Nomad', 'Advantage', 'Advantage Edition', 'Generation', 'Evan', 'RM', 'RM 5', '4-travel', 'Fortero', 'Globebus Active', 'Globebus T 1', 'Just Camp Active', 'Just Go Active', 'Trend Active', 'E.home Eco', 'Multijet 140', '580 V'],
  'Dreamer': ['D68', 'D43 UP', 'D55', 'D55 UP', 'CAMPER SPORT', 'CAMPER FIVE', 'D43 SELECT', 'D43 UP SELECT', 'CITY CAMP SELECT', 'CAP LAND SELECT', 'D55 SELECT', 'D68 SELECT', 'D68 UP SELECT', 'D62 SELECT', 'LIVING VAN SELECT', 'FAMILY VAN SELECT', 'CAMPER VAN XL SELECT'],
  'Dovra': ['RIG X-610', 'RIG X-750', 'RIG S-610', 'RIG S-750'],
  'Eifelland': ['Holiday', 'Deseo', 'Sunshine', 'Relax', 'Businesscamper', 'Workcation', 'Eifelland Classic', 'HD Camper', 'Executive', 'NordVan'],
  'Elnagh': ['Magnum', 'E-Van', 'T-Loft', 'Baron', 'Bahron', 'Baron 26', 'Baron 28', 'Clipper', 'Columbia', 'Cutter', 'Dinghy', 'Doral', 'Duke', 'Marlin', 'Baron Compact', 'E-Van Next', 'A-Loft', 'I-Loft'],
  'Etrusco': ['CV 600 BB', 'CV 600 DB', 'CV 640 SB', 'V 6.8 SF', 'V 7.2 GF', 'T 6.6 SF', 'T 6.8 SF', 'T 6.9 DF', 'T 6.9 SF', 'T 7.3 QF', 'A 6.9 DB', 'A 6.9 SB', 'A 7.0 SF', 'I 7.2 GF', 'I 7.3 QF', '6.6 SF', '6.9 SF', '7.0 SF', '7.3 QF', 'Base T 5.9', 'Base T 6.6', 'Base T 6.9', 'Base A 6.9', 'CV Plus', 'Urban Camper'],
  'Eurocamp': ['TC 310', 'TC 350', 'TC 540', 'TC 630', 'Sprinter', 'Ducato'],
  'Eura Mobil': ['Van 635 EB', 'Van 635 HB', 'Activa One', 'Activa One 570 HS', 'Activa One 650 HS', 'Activa One 690 HB', 'A 535 LS', 'A535LS', 'A 550 LS', 'A 660 EB', 'A 700 EB', 'Profila 660 HB', 'Profila T', 'Profila T 660 EB', 'Profila T 670 EB', 'Profila T 670 SB', 'Profila T 680 HS', 'Profila T 696 EB', 'Profila T 696 HB', 'Profila T 700 EB', 'Profila T 720 EF', 'Profila T 720 QB', 'Profila T MB', 'Profila T Freestyle', 'Profila RS', 'Profila RS 695 HB', 'Profila RS 720 EF', 'Profila RS 730 EB', 'Contura', 'Contura 696 HB', 'Contura 720 EF', 'Contura 742 EB', 'Contura 760 EB', 'Contura 760 EF', 'Contura 767 HS', 'Xtura', 'Xtura 760 EB', 'Integra Line', 'Integra Line 695 HB', 'Integra Line 720 EB', 'Integra Line 730 EB', 'Integra Line 730 QF', 'Integra Line IL 720 EB', 'Integra Line IL 730 EB', 'Integra Line GT', 'IL 720 EB', 'IL 730 EB', 'Integra 890 EB', 'Integra 900 EB', 'Profila One', 'Terrestra', 'C 742 EB'],
  'Fendt': ['Apero', 'E-Van', 'Bianco', 'Bianco Activ', 'Bianco Selection', 'Bianco Sportive', 'Tendenza', 'Diamant', 'Saphir', 'Opal', 'Topas', 'Platin', 'Brillant', 'Larimar', 'Next', 'Vienna'],
  'Fiat': ['Ducato', 'Ducato Selbstausbau', 'Ducato Campingbus', 'Talento Campingbus', 'Talento', 'Scudo', 'Scudo Campingbus', 'Doblo'],
  'Citroën': ['Jumper', 'Jumper Selbstausbau', 'Jumper Campingbus', 'SpaceTourer', 'Jumpy', 'Jumpy Campingbus', 'Berlingo'],
  'Fleurette': ['Baxter', 'Mayflower', 'Wincester', 'Migrateur', 'Magister', 'Discover', 'Elister', 'Black Pearl'],
  'Florium': ['Black Pearl', 'Baxter', 'Migrateur', 'Mayflower', 'Magister', 'Discover', 'Wincester', 'Elister'],
  'Ford': ['Nugget', 'Nugget Plus', 'Nugget Trail', 'Transit Custom Nugget', 'Transit', 'Transit Custom', 'Transit 135 T 350', 'Transit Selbstausbau', 'Transit Custom Campingbus', 'Transit Mk2', 'Econoline'],
  'Forest River': ['Forester', 'Forester 2401 WS', 'Forester 2501 TS', 'Sunseeker', 'Sunseeker MBS', 'Sunseeker LE', 'Solera', 'Solera 22', 'Solera 24', 'Coachmen', 'Cross Trek'],
  'Hehn Mobil': ['590 HS', '690 HS', '590 HS Sprinter 313 CDI', '670 EB', '740 EB', '750 EB', 'Sprinter Vario'],
  'Forster': ['FV 599 HB', 'FV 541 HBL', 'FV 599 EBL', 'FV 636 EBF', 'FV 649 EB', 'FT 599 HB', 'FT 649 EB', 'FT 699 HB', 'FI 649 EB', 'FA 649 EB', 'T 599 HB', 'T 649 EB', 'T 699 EB NB', 'T 699 HB', 'T 745 EB', 'VB 599 HB', 'VB 649 EB', 'VB 699', 'VB 726', 'Livin Up', 'Livin Up Pro', 'Vibe', 'Travel Line', 'Vantasy', 'Vantasy 636', 'Coupé', 'Youngster'],
  'Frankia': ['PLATIN', 'PLATIN PURE', 'TITAN', 'NOCTRA', 'NOCTRA Cruiser', 'F-Line', 'F-Line I 7400 GD', 'F-Line I 7900 GD', 'TOGETHER', 'TOGETHER MT', 'NEO', 'NEO MT', 'NEO MT 7', 'NEO MT 7400', 'NEO MI', 'NEO MI BLACK LINE', 'NOW', 'FINAL EDITION', 'Comfort Class', 'ExclusiveClass', 'Holiday Class', 'Luxury Class', 'M-Line', 'M-Line 600', 'M-Line 640', 'M-Line 680', 'M-Line 700', 'M-Line 740', 'M-Line 780', 'I-Line', 'I-Line 680', 'I-Line 700', 'I-Line 740', 'I-Line 7400 GD', 'A-Line', 'A 600', 'A 640', 'A 680', 'A 700', 'A 740', 'A 7400', 'A 780', '600', '640', '680', '700', '740', '780', '840'],
  'GiottiLine': ['Siena 330', 'Siena 395', 'Siena 430', 'Siena 440', 'Toscan 330', 'Toscan 430', 'Toscan 440', 'GiottiCompact C32', 'GiottiCompact C33', 'GiottiVan 54T', 'GiottiVan 60T', 'GiottiVan 60F', 'Therry T30', 'Therry T31', 'Therry T32', 'Therry T34', 'Therry T36', 'Therry T38'],
  'Globe-Traveller': ['Explorer', 'Voyager', 'Falcon', 'Pathfinder'],
  'Globecar': ['Roadscout', 'Globestar', 'Globescout', 'Campscout', 'Roadstar', 'Summit', 'Summit Prime', 'Summit Shine', 'Globestar 600', 'Globestar 640', 'Globescout Plus', 'D-Line', 'H-Line'],
  'Glücksmobil': ['A', 'C', 'S', 'T', 'VAN'],
  'HRZ': ['Tango', 'Mambo', 'Life', 'Chamäleon', 'Beach', 'Joy', 'Dream', 'Star', 'Family L', 'Toscana', 'Biker', 'Freedom', 'Sahara', 'Casablanca', 'Safari', 'Casablanca L', 'Casablanca U', 'Racing', 'Longus', 'Reha Camper 2', 'Reha Camper 2+'],
  'Hobby': ['OnTour C', 'OnTour T', 'OnTour A', 'OnTour Van', 'Prestige T', 'Prestige I', 'Prestige Van', 'Prestige Van First Edition', 'Maxia T', 'Maxia I', 'Maxia Van', 'Optima', 'Optima De Luxe', 'Optima De Luxe T 65 GE', 'Optima Premium', 'Optima Premium T 65 GE', 'Optima Ontour', 'Premium', 'Siesta', 'Siesta Nice', 'Sphinx', 'Toskana', 'Toskana Exclusive', 'Van', 'Vantana', 'Vantana De Luxe', 'Vantana Ontour', 'Beachy', 'De Luxe', 'De Luxe Easy', 'De Luxe Edition', 'Excellent', 'Excellent Easy', 'Excellent Edition', 'Excellent 540 FU', 'Excellent 540 KMFe', 'Excellent 560 CFe', 'Excellent 560 KMFe', 'Excellent 560 LU', 'Excellent 560 UL', 'Excellent 650 KMFe', 'Excellent 650 UFe', 'Excellent 720 UKFe', '540 FU', '560 UL', '560 LU', '650 KMFe', 'Alkoven'],
  'Hymer': ['B-Klasse MasterLine', 'B-Klasse ModernComfort T', 'B-Klasse ModernComfort I', 'B-Klasse White Line', 'B-Klasse SL', 'B-Klasse DynamicLine', 'B 504', 'B 514', 'B 524', 'B 534', 'B 544', 'B 554', 'B 564', 'B 574', 'B 584', 'B 594', 'B 614', 'B 654', 'B 655', 'B-ML T 780', 'B-MC T 550', 'B-MC T 580', 'B-MC T 600', 'B-MC T 680', 'B-MC I 690', 'Exsis-t 470', 'Exsis-t 474', 'Exsis-t 504', 'Exsis-t 580', 'Exsis-t 588', 'Exsis-t 678', 'Exsis-i 504', 'Exsis-i 580', 'Exsis-i 588', 'Exsis-i 678', 'ML-T 540', 'ML-T 560', 'ML-T 570', 'ML-T 580', 'ML-T CrossOver', 'ML-T CrossTrail', 'ML-T Xperience', 'Venture S', 'Grand Canyon S', 'Grand Canyon S CrossOver', 'Grand Canyon S 600', 'Grand Canyon S 700', 'Free 540', 'Free 600', 'Free S 600', 'Free Campus', 'DuoMobil', 'Tramp S 585', 'Tramp S 695', 'Tramp 544', 'Tramp 615', 'Tramp 655', 'Tramp 695', 'Tramp CL', 'Tramp T', 'Tramp I', 'Tramp Compact', 'Sydney', 'Santa Fe', 'Yellowstone', 'GT-S', 'Redwood', 'Eriba Touring', 'Eriba Touring 540', 'Eriba Touring Troll', 'Eriba Touring Triton', 'Eriba Feeling', 'Eriba Nova', 'Eriba Nova GL', 'Eriba Exciting', 'Eriba Pan', 'Hymercar', 'Hymermobil', 'Hymer Van', 'Van 314', 'Van 322', 'Van 502', 'Van 512', 'Van 514', 'Van 522', 'Van 600', 'Van 614', 'S 520', 'S 555', 'S 585', 'S 660', 'S 700', 'S 800', 'T-Klasse S', 'T-Klasse', 'S-Klasse', 'StarLine', 'Camp', 'Car', 'B-ML I BlackLine', 'B-ML T BlackLine', 'Exsis-i Pure', 'Exsis-t Pure', 'Grand Canyon S CrossTrail', 'Grand Canyon S Xperience'],
  'Ilusion': ['I.Lux', 'XMK', 'Premium', 'Fusion'],
  'Itineo': ['PS740', 'PF600', 'PC640', 'PJ700', 'PM740', 'CM660', 'CJ660', 'JC740', 'SB740', 'MB740', 'FC650', 'MC740', 'PS700', 'CS660', 'SBD700', 'COZI', 'FAMILI COMPACT', 'FAMILI'],
  'Joa Camp': ['60F', '75T', '75Q', '70T', '70Q', '54G', '60G', '63T', '75TB', '75QB'],
  'Joint': ['Spaceline', 'E-Serie', 'J-Serie', 'S-Serie', 'T-Serie', 'X-Serie', 'Z-Serie', 'New Life', 'Elegance'],
  'Kabe': ['Imperial', 'Crown', 'Royal', 'Novum', 'Classic', 'Travel Master', 'Van', 'Edelstein', 'Ametist', 'Smaragd', 'Safir', 'Rubin', 'Onyx', 'Briljant', 'Hacienda', 'Estate', 'Abisko Van', 'Gemstone'],
  'Karmann': ['Davis', 'Dexter', 'Duncan', 'Davis Lifestyle', 'Davis Trendstyle', 'Dexter 4x4', 'Gipsy', 'Cheetah', 'Distance Wide'],
  'Knaus': ['Van TI', 'Van TI 550 MD', 'Van TI 600 MG', 'Van TI 650 MEG', 'Van TI 650 MEG Vansation', 'Van TI 650 MF', 'Van TI 700 MEG', 'Van TI Plus', 'Van TI Plus 650 MEG', 'Van TI Plus 700 LF', 'Van TI Plus 700 MEG', 'Van TI Vansation', 'Van TI MAN', 'Van TI Plus MAN', 'Van I', 'Van I 550 MD', 'Van I 650 MEG', 'Van I 700 MEG', 'Van Wave', 'L!VE TI', 'L!VE TI 590 LF', 'L!VE TI 650 MEG', 'L!VE Wave', 'L!VE Wave 650 MG', 'L!VE I', 'L!VE I 650 MEG', 'L!VE I 700 MEG', 'L!VE Traveller', 'Sky TI', 'Sky TI 590 LF', 'Sky TI 650 MF', 'Sky TI 650 MEG', 'Sky TI 700 MEG', 'Sky TI Platinum Selection', 'Sky Wave', 'Sky Wave 650 MG', 'Sky I', 'Sky I 700 LEG', 'Sun TI', 'Sun TI 700 LX', 'Sun I', 'Sun I 700 LX', 'Sun I 900 LX', 'Sun Liner', 'Sun Liner 900 LX', 'BoxDrive', 'BoxDrive 600 ME', 'BoxDrive 680 ME', 'BoxLife', 'BoxLife 540 MQ', 'BoxLife 600 ME', 'BoxLife 600 MQ', 'BoxLife 630 ME', 'BoxLife Pro', 'BoxLife Pro 600 MQ', 'BoxLife Platinum Selection', 'BoxStar', 'BoxStar 540', 'BoxStar 600', 'BoxStar 600 Solution', 'BoxStar 630', 'BoxStar 630 Solution', 'BoxStar Road', 'BoxStar Road 540 MQ', 'BoxStar Road 600 ME', 'BoxStar Road 600 MQ', 'BoxStar Road 630 ME', 'BoxStar Freeway', 'BoxStar Freeway 540', 'BoxStar Freeway 600', 'BoxStar Freeway 630', 'BoxStar Street', 'BoxStar Street 540', 'BoxStar Street 600', 'BoxStar Street 630', 'BoxStar Lifetime', 'BoxTime', 'Sport&Fun', 'CUVision', 'CUVision 500 MQ', 'YASEO', 'Sport', 'Südwind', 'Südwind 460 EU', 'Südwind 500 EU', 'Südwind 540 UE', 'Südwind 580 QS', 'Südwind 590 UF', 'Südwind Silver Selection', 'Südwind Black Selection', 'Starclass', 'Deseo', 'Deseo Plus', 'Deseo Transport', 'Travelino', 'Sky Traveller', 'Sun Traveller', 'Eurostar', 'Eurostar 685', 'Azur', 'Tourer Van', 'Tourer Van CUV 500 MQ', 'Tourer Van CUV 500 MQ Vision', 'Tourer Van CUV 600 MQ', 'Tourer CUV', 'Tourer CUV 500 MQ', 'Tourer CUV 600 MQ', 'Traveller', 'Traveller 685', 'Traveller 700', 'Fiat Van', 'E.Power Drive'],
  'LMC': ['Tracer', 'Tourer', 'Cruiser', 'Innovan', 'Innovan 540', 'Innovan 600', 'Breezer', 'Sassino', 'Style', 'Style Lift', 'Vivo', 'Musica', 'Exquisite VIP', 'e:dero', 'Videro', 'Videro V 643G', 'Videro V 663G', 'V 643G', 'V 663G', 'Tandero', 'Luxus', 'Tourer Alcove'],
  'La Strada': ['NOVA', 'NOVA M', 'REGENT', 'REGENT S', 'REGENT E', 'AVANTI', 'AVANTI EB', 'AVANTI H', 'AVANTI L', 'AVANTI C', 'AVANTI F', 'NOVA EB', 'REGENT EB', 'AVANTI E'],
  'Laika': ['Ecovip', 'Ecovip H', 'Ecovip L', 'Ecovip Titanio', 'Kreos', 'Kreos H', 'Kreos L', 'Kreos 4009', 'Kreos 5009', 'Kreos 5010', 'Kreos 6009', 'Kreos 7009', 'Kreos 8009', 'Kosmo', 'Kosmo 309', 'Kosmo 409', 'Kosmo 509', 'Kosmo 512', 'Kosmo 612', 'Kosmo Campervan', 'Kosmo Supremo', 'Kosmo L', 'Kosmo H', 'Rexosline', 'X'],
  'Le Voyageur': ['Eterna', 'Héritage', 'LV 7.5', 'LV 7.8', 'LV 8.0', 'LV 8.5', 'LV 9.0', 'Liner 8.8', 'Liner 9.0', 'Liner 10.0', 'Explorer', 'LVX'],
  'Malibu': ['Van 540 DB', 'Van 540 LE', 'Van 600 DB', 'Van 600 LE', 'Van 640 LE', 'Van Charming GT', 'Van Charming Coupé', 'Van Comfort GT', 'Van Diversity', 'Van First Class', 'Genius 600', 'Genius 640', 'T 430', 'T 430 LE', 'T 460', 'T 460 LE', 'I 430', 'I 430 LE', 'I 440 LE', 'I 460', 'I 460 LE', 'I 500', 'I 500 DB', 'Carthago Malibu', 'Compact', 'Charming', 'First Class Two Rooms', 'Relax'],
  'McLouis': ['Glamys', 'Mc4', 'Nevis', 'Menfys', 'Lagan', 'Steel', 'Tandy', 'Glen', 'Carat', 'Fusion', 'Sovereign'],
  'MegaMobil': ['Mega Lounge', 'Mega Classic', 'Mega Re-Aktiv', 'Mega Sport', 'Mega Revolution', '4x4 Camper', 'Mega Vario Aktiv', 'Mega Twin'],
  'Mercedes-Benz': ['Marco Polo', 'Marco Polo Horizon', 'Marco Polo Activity', 'T-Klasse', 'V-Klasse', 'Sprinter', 'Sprinter 312', 'Sprinter 313 CDI', 'Sprinter 316 CDI', 'Sprinter 319 CDI', 'Sprinter Selbstausbau', 'Vito', 'Vito Marco Polo', 'Citan', 'EQV', 'Esterel', 'Unimog 1300L', 'Unimog'],
  'Miller': ['Ontario', 'Winnipeg', 'Erie', 'Toronto', 'M-Liner', 'Maryland', 'Alaska', 'Montana', 'Michigan', 'Ohio', 'New York', 'Louisiana', 'Colorado', 'Virginia', 'Nevada', 'Mississippi', 'Kansas'],
  'Mobilvetta': ['Admiral', 'Krosser', 'Kea P', 'Kea I', 'K-Yacht Tekno Line', 'Kea Kompakt', 'K-Silver', 'Kea M'],
  'Mooveo': ['Van 54', 'Van 60', 'Van 63', 'Van 64', 'Van 65', 'TEI 60 SBH', 'TEI 70 EBH', 'TEI 74', 'TEI 74 DF', 'TEI 74 EBH', 'TEI 74 QBH', 'VOI 74', 'VOI 78', 'AK 74', 'AK 78', 'Campervan', 'Campervan 2'],
  'Morelo': ['Home', 'Loft', 'Loft Liner', 'Loft Premium', 'Loft Premium Liner', 'Palace', 'Palace Liner', 'Palace Liner S-Way', 'Empire Liner', 'Grand Empire', 'Manor'],
  'Niesmann+Bischoff': ['iSmove', 'iSmove 6.9 E', 'iSmove 7.3 E', 'Smove', 'Arto', 'Arto 76 E', 'Arto 76 EK', 'Arto 76 F', 'Arto 76 L', 'Arto 78 E', 'Arto 78 EK', 'Arto 78 F', 'Arto 79 EK', 'Arto 88 LF', 'Flair', 'Flair 830 LE', 'Flair 880 LF', 'Flair 920 LE', 'Clou', 'Clou Liner', 'Clou Liner I 880 LF'],
  'NobelART': ['T-5000', 'T-6000', 'T-7000', 'A-7000', 'A-9000', 'Liner'],
  'Notin': ['Progress', 'Excel', 'NotinLiner', 'Bilbao', 'Lorca', 'Lindau', 'Avila', 'Bruges', 'Vera', 'Rubi', 'Calvia', 'Exclusiv', 'Excel Evolution', 'I.Progress', 'Lerida', 'Ostrava', 'Vitoria', 'Palma'],
  'Orangecamp': ['T-Serie', 'A-Serie', 'K-Serie', 'Crafter', 'Inkognito'],
  'P.L.A.': ['M Klasse', 'S Klasse', 'Siena', 'GiottiVAN', 'GiottiCompact', 'Toscan'],
  'Panama': ['P09', 'P10+', 'P12+', 'P10H', 'Urban 11', 'Peak P10+', 'P50+', 'P59+'],
  'Phoenix': ['Maxi', 'Midi', 'Top-Alkoven', 'Top-Liner', 'Maxi-Liner', 'TopX-Alkoven', 'MIDI Alkoven', 'MIDI Liner', 'MAXI Alkoven', 'TOPX Liner'],
  'Pilote': ['Pacific Expression', 'Pacific Evidence', 'Pacific P600', 'Pacific P650', 'Pacific P690', 'Pacific P696', 'Pacific P696U', 'Pacific P740', 'Pacific P746', 'P600', 'P650', 'P690', 'P696', 'P696U', 'P740', 'P746', '690', '696', '696 Evidence', '740 Evidence', 'P650 Evidence', 'P690 Evidence', 'P696 Evidence', 'P696U Evidence', 'P746 Evidence', 'Galaxy Expression', 'Galaxy Evidence', 'Galaxy G600', 'Galaxy G650', 'Galaxy G700', 'Galaxy G740', 'Atlas', 'Atlas A630', 'Atlas A650', 'Atlas A690', 'Van', 'Van V540', 'Van V600', 'Van V630', 'Van V633', 'Van Evidence', 'Van X-Edition', 'Explorateur', 'Aventura', 'Reference', 'Sensation', 'Vega', 'Foxy Van'],
  'Pössl': ['Summit', 'Summit 540', 'Summit 600', 'Summit 600 Plus', 'Summit 640', 'Summit 640 Plus', 'Summit Shine 540', 'Summit Shine 600', 'Summit Shine 640', 'Summit Prime 540', 'Summit Prime 600', 'Summit Prime 640', 'Roadstar 540', 'Roadstar 600', 'Roadstar X', 'Roadstar XT', 'Roadcruiser', 'Roadcruiser XL', 'Roadcruiser Revolution', 'Roadcamp', 'Roadcamp R', '2Win', '2Win Plus', '2Win S', '2Win S Plus', '2Win R', '2Win R Plus', 'Vario 545', 'Vario 600', 'D-Line', 'H-Line', 'X-Line', 'Vanline', 'P2 Relax', 'P2 Plus Relax', 'Trenta', 'Trenta 540', 'Trenta 600', 'Trenta 640', 'Campster', 'Vanster', 'Campstar', 'Vanstar', 'e-Vanster', 'Concorde Compact', 'Concorde Compact 540', 'Concorde Compact 600', 'Concorde Compact Plus', 'Concorde Trium', 'Concorde Trium 600', 'Concorde Trium 640', 'Concord Compact', 'Concord-Compact', 'Globecar Campscout', 'Globecar Globescout', 'Globecar Globestar', 'Globecar Roadscout', 'Globecar Summit', 'Globecar 540', 'Globecar 600', 'Globecar 640', 'Crosscamp', 'Crosscamp Lite', 'Crosscamp Flex', 'Crosscamp Tour', 'Crosscamp Toyota'],
  'Randger': ['R490', 'R499', 'R530', 'R535', 'R540', 'R550', 'R555', 'R560', 'R570', 'R602', 'R640', 'R600', 'R635'],
  'Rapido': ['C50', 'C55', 'C86', 'V55', 'V62', 'V65', 'V68', '606F', '636F', '666F', '686F', '696F', '850F', '854F', '866F', '896F', '8066dF', '8096dF', 'M66', 'M96', 'Distinction i66', 'Distinction i96', 'Distinction i166', 'Distinction i196', 'Randonneur 970 M', 'Randonneur 940 M', 'Randonneur 10002', 'C03', 'C66'],
  'Renault': ['Master', 'Master Selbstausbau', 'Trafic', 'Trafic Campingbus', 'Trafic Selbstausbau', 'Trafic SpaceNomad', 'Kangoo', 'Estafette'],
  'Reimo': ['Trio High Style', 'Triostyle', 'City Van', 'Camp', 'Camp Maxi', 'EQV', 'Multi Style', 'Active', 'Star', 'Free Van'],
  'Rimor': ['Horus', 'Kilig', 'Sarus', 'Super Brig', 'Sailer', 'Seal', 'Katamarano', 'Rimor Van', 'Bliss', 'Europe', 'Europe 77', 'Europe 88', 'Europe 90', 'Europeo', 'Evo', 'Evo 5', 'Evo 75', 'Evo 95', 'Evo 95 Plus', 'Sweden', 'Sweden 56', 'Sweden 75', 'Nemho'],
  'Roadcar': ['R 540', 'R 600', 'R 601', 'R 640', 'R 540 Shine', 'R 600 Shine', 'R 640 Shine'],
  'Robeta': ['Ares', 'Helios', 'Kronos', 'Apollo', 'Adonis', 'Womondo', 'Air'],
  'Roller Team': ['Kronos 265 TL', 'Kronos 266 TL', 'Kronos 284 TL', 'Kronos 284 TL Edition', 'Kronos 285 TL', 'Kronos 290 TL', 'Kronos Fit', 'Zefiro 265 TL', 'Zefiro 266 TL', 'Zefiro 285 TL', 'Zefiro 287 TL', 'Zefiro 585', 'Zefiro 690', 'Zefiro 696', 'Zefiro Plus', 'Zaffira', 'Zaffira 585', 'Zaffira 690', 'Zaifira 585', 'Livingstone 2', 'Livingstone 5', 'Livingstone Sport', 'Livingstone GO', 'Livingstone Advance', 'Pegaso 590', 'Pegaso 740', 'Pegaso 745', 'T-Line 590', 'T-Line 690', 'T-Line 740', 'Auto-Roller', 'Auto-Roller 1', 'Auto-Roller 284 TL', 'Auto-Roller 284 TL Kronos Edition', 'Auto-Roller 285 TL', 'Granduca'],
  'Schwabenmobil': ['Florida 5.9 L', 'Florida Multitalent', 'Florida Tango', 'Florida Family L', 'Florida Family Q', 'Florida Travel', 'Florida Reha Camper'],
  'SEA': ['Sharky', 'Gigant', 'A 610', 'Dart', 'Extreme 369', 'Sloop'],
  'Soma Camp': ['SOMA VAN', 'T680 EB', 'T700 EB', 'T 650 EB', 'L-LINE', 'Comfort 530 E', 'Family 560 FMK', 'Doogi 560 FMK'],
  'Sun Living': ['Lido A35', 'Lido A45', 'Lido M45', 'Lido S42', 'Lido S49', 'S 70 SP', 'S 70 SL', 'S 70 DK', 'S 75 SL', 'A 70 DK', 'A 70 SP', 'V 55 SP', 'V 60 SP', 'V 65 SL', 'C 70 DK', 'Lido M 49'],
  'Sunlight': ['Cliff', 'Cliff 540', 'Cliff 541', 'Cliff 600', 'Cliff 601', 'Cliff 640', 'Cliff Adventure', 'Cliff Adventure Edition', 'Cliff X', 'Cliff 4x4', 'Cliff 4x4 Greentrek', 'Vanlife', 'Vanlife V 60', 'Vanlife V 66', 'Vanlife V 69', 'V 60', 'V 60 Adventure Edition', 'V 66', 'V 66 Adventure Edition', 'V 69', 'V66', 'T 58', 'T 60', 'T 64', 'T 65', 'T 65 S', 'T 66', 'T 67', 'T 68', 'T 69', 'T 670', 'T 670 S', 'T58', 'T64', 'T65', 'T66', 'T67', 'T68', 'T69', 'T670', 'T670S', 'I 64', 'I 68', 'I 69', 'A 68', 'A 70', 'A 72', 'C-Klasse', 'Ford Adventure Edition', 'Ford T670S'],
  'TEC': ['Freetec', 'Freetec 600', 'Freetec 660', 'Freetec 694 XS', 'Freetec 700', 'Rotec', 'Rotec 600', 'Rotec 660', 'Rotec 700', 'I-TEC', 'AdvanTec', 'Travel King', 'Travel King 460K', 'Travel King 490K', 'Tour live', 'Weltbummler', 'Travelbird'],
  'Tabbert': ['ROSSINI', 'DA VINCI', 'PEP', 'VIVALDI', 'PUCCINI', 'CELLINI', 'PANTIGA', 'CAZADORA', 'SENARA'],
  'Tourne': ['Select', 'Cruise'],
  'Trigano': ['Tribute', 'Tribute 670', 'Tribute 680', 'Tribute T 720', 'Auto Trail', 'Sun Roller', 'Mooveo', 'Caravan', 'Sun Living', 'Silver', 'Cheroky', 'Sequoia', 'Ceylan', 'Lagun', 'Zambesi', 'Galleon', 'Mini Freestyle', 'Rubis'],
  'VANTourer': ['540 D', '600 D', '600 L', '630 L', 'Urban', '600 Ds', 'GO!'],
  'VARIO mobil': ['VARIO Star', 'VARIO Perfect', 'VARIO Alkoven', 'VARIO Signature', 'VARIO Classic'],
  'Volkswagen': ['California', 'California Beach', 'California Coast', 'California Ocean', 'Grand California', 'Grand California 600', 'Grand California 680', 'Caddy California', 'ID. Buzz', 'ID. Buzz GTX', 'Transporter', 'Transporter T4', 'Transporter T5', 'Transporter T6', 'Transporter T6.1', 'T4 Syncro', 'T4 California', 'T5 California', 'T6 California', 'T6 Selbstausbau', 'T6.1 California', 'T7 Multivan', 'Crafter', 'Crafter Selbstausbau', 'Multivan', 'Multivan Life', 'Multivan Style', 'Caravelle', 'Vanagon', 'Eurovan', 'Amarok'],
  'Weinsberg': ['CaraCompact 540 MQ', 'CaraCompact 600 MF', 'CaraCompact 600 MEG', 'CaraCompact 640 MEG', 'CaraCompact 650 MEG', 'CaraCompact Suite 640 MEG', 'CaraCompact Edition PEPPER', 'X-PEDITION', 'Cara Core', 'Cara Core 650 MEG', 'Cara Core 700 MEG', 'Cara Suite', 'Cara Suite 650 MF', 'Cara Suite 700 ME', 'Cara Suite 700 MEG', 'Cara Tour', 'Cara Tour 541 MQ', 'Cara Tour 600 MQ', 'Cara Tour 630 MEG', 'Cara Tour 631 ME', 'Cara Loft', 'Cara Loft 550 MG', 'Cara Loft 650 MF', 'Cara Loft 700 MEG', 'CaraSuite 650 MF', 'CaraSuite 700 ME', 'CaraSuite 700 MEG', 'CaraHome 550 MG', 'CaraHome 600 DKG', 'CaraHome 650 DG', 'CaraHome 700 DG', 'CaraCore 650 MEG', 'CaraCore 700 MEG', 'CaraLoft 550 MG', 'CaraLoft 650 MF', 'CaraLoft 700 MEG', 'CaraBus', 'CaraBus 540 MQ', 'CaraBus 600 MQ', 'CaraBus 601 MQ', 'CaraBus 630 ME', 'CaraBus 630 MEG', 'CaraBus Edition [FIRE]', 'CaraBus GREY', 'CaraLife', 'CaraLife 630 LQ', 'CaraTour 541 MQ', 'CaraTour 600 MQ', 'CaraTour 631 ME', 'CaraTour 630 MEG', 'CUVolution', 'X-Cursion CUV 500 MQ', 'X-Cursion VAN 500 MQ', 'X-Pedition 545 MF', 'OUTLAW', 'CaraOne', 'CaraOne Edition', 'CaraTwo', 'CaraCito', 'T 650 MEG', 'T 600 MQ'],
  'Westfalia': ['Club Joker', 'Kepler', 'Jules Verne', 'Kelsey', 'Kipling', 'Columbus', 'Sven Hedin', 'James Cook', 'Wave', 'Joker', 'Meridian', 'Kepler One', 'Kepler Six', 'Club Joker Urban', 'Amundsen'],
  'Wilk': ['Deluxe', 'Sento', 'Vida', 'Eterno', 'Safari', 'S3', 'S4', 'De Luxe', 'Stern', 'Sport'],
  'Wingamm': ['Oasi 540', 'Oasi 610', 'Oasi 690', 'Brownie', 'Rookie', 'City Pro'],
  'XGO': ['XVAN', 'XVAN 104 Allin', 'XVAN 105', 'XCAMP', 'Dynamic 21', 'Dynamic 22', 'Dynamic 23', 'Dynamic 25', 'Dynamic 26', 'Dynamic 27', 'Dynamic 33', 'Dynamic 35', 'Dynamic 95G'],
  'Yucon': ['K-peak', '6.0 GD', '6.0 BD', 'V-city', '7.0 GD'],
  'Action Mobil': ['Atacama', 'Atacama 7900', 'Atacama 9900', 'Global X', 'Global XR', 'Global XRX', 'Globaler 7400', 'Desert Challenger'],
  'Adventure': ['Trail Sport', 'Trail Lite', 'Trailblazer'],
  'Airstream': ['Interstate', 'Interstate 19', 'Interstate 24', 'Atlas', 'Westfalia', 'Travel Trailer'],
  'Alpenkreuzer': ['Mini', 'Maxi'],
  'American Coach': ['American Eagle', 'American Tradition', 'American Dream'],
  'Avento': ['Compact', 'Comfort', 'Excellent'],
  'Auto-Sleeper': ['Symbol', 'Warwick', 'Broadway', 'Bourton', 'Burford', 'Wave', 'Kingham', 'Nuevo', 'Fairford', 'Stanton', 'Wendover'],
  'Bavaria-Camper': ['T 65 GS', 'T 70 EBH', 'T 73 GS'],
  'Bunk Campers': ['Aero', 'Vista', 'Solo', 'Roadie', 'Grande'],
  'Capron': ['T 348', 'T 449', 'I 449', 'A 461', 'Touch'],
  'Coachmen': ['Beyond', 'Cross Trek', 'Freedom Express', 'Mirada', 'Galleria', 'Nova', 'Leprechaun', 'Sportscoach'],
  'CrossCamp': ['Lite', 'Flex', 'Tour', 'Toyota', 'Mercedes'],
  'Dynamax': ['Isata', 'Force HD', 'DX3', 'Europa'],
  'Erwin Hymer Center': ['Sonderausführung'],
  'Forester': ['Forester 2401 WS', 'Forester 2501 TS', 'Forester 2861 DS', 'Forester 3011 DS'],
  'Holiday Rambler': ['Endeavor', 'Navigator', 'Vacationer', 'Scepter'],
  'Home-Car': ['Z-Line', 'A-Line', 'B-Line', 'X-Line'],
  'Hyundai': ['Staria', 'Staria Camper', 'H-1', 'H350'],
  'Hethon': ['BJ7', 'BJ8'],
  'Italjet': ['Caravan'],
  'Iveco': ['Daily', 'Daily Selbstausbau', 'Daily 4x4'],
  'Jayco': ['Greyhawk', 'Redhawk', 'Granite Ridge', 'Melbourne', 'Seneca'],
  'Jurgens': ['Penta', 'Sungazer', 'Fleetline'],
  'KIP': ['Vision', 'Vision XL', 'Eclipse', 'Hummerland'],
  'Knaus Tabbert': ['Sonstiges Modell'],
  'Lazy Daze': ['Mid Bath', 'Rear Bath', 'Twin King'],
  'Lord Munsterland': ['Capitano', 'Tornado', 'Caprice'],
  'Mader': ['Camptourist', 'CT 6-2', 'Touring'],
  'Mercedes': ['Sprinter', 'Marco Polo', 'Vito', 'V-Klasse', 'T-Klasse', 'EQV', 'Esterel'],
  'Newmar': ['Dutch Star', 'Mountain Aire', 'New Aire', 'Ventana', 'Bay Star', 'Canyon Star'],
  'Niesmann Bischoff': ['iSmove', 'Arto', 'Flair', 'Clou', 'Smove'],
  'Nissan': ['NV200', 'NV300', 'NV400', 'Primastar Camper', 'Interstar Camper'],
  'Nordstar': ['Camp 4', 'Camp 6', 'Camp 8'],
  'Opel': ['Vivaro', 'Movano', 'Zafira Life', 'Combo Life'],
  'Pendragon': ['Sonstiges Modell'],
  'Peugeot': ['Boxer', 'Traveller', 'Expert', 'Rifter', 'Boxer Selbstausbau'],
  'Predom': ['Niewiadow', 'Tarpan'],
  'Procamp': ['Compact', 'Comfort'],
  'QEK': ['Junior', 'Aero'],
  'Roadtrek': ['Zion', 'Adventurous', 'CS Adventurous', 'SS Agile', 'Slumber', 'Pivot'],
  'Sailler': ['Compact', 'Comfort'],
  'Sportberger': ['Ammersee', 'Starnberg', 'Tegernsee'],
  'Storebro': ['Sonstiges Modell'],
  'Sun Roller': ['Queen', 'Princess', 'Lord', 'King', 'Prince'],
  'Sunlight Wohnwagen': ['Njoy', 'C-Klasse'],
  'Thor Motor Coach': ['ACE', 'Axis', 'Vegas', 'Outlaw', 'Quantum', 'Tiburon', 'Compass', 'Gemini'],
  'Tiffin': ['Allegro', 'Phaeton', 'Wayfarer', 'Zephyr'],
  'Toyota': ['Proace', 'Proace Verso', 'Proace City', 'Hiace Camper', 'Hilux Camper'],
  'Vansports': ['VS30', 'PMR'],
  'Volkner': ['Performance', 'Performance Bus', 'Performance S'],
  'Volkner Mobil': ['Performance', 'Performance S', 'Performance L'],
  'Wofa': ['QEK', 'Junior'],
  'Wohnmobil-Manufaktur': ['Sonderausführung'],
  'Wohnwagon': ['Wagon S', 'Wagon M', 'Wagon L'],
  'Andere': ['Sonstiges Modell']
};

// Sorted manufacturer list for Wohnmobile
export const popularManufacturers = Object.keys(manufacturerModels).sort();

// Comprehensive manufacturer-to-model mapping for Wohnwagen (Caravans)
export const wohnwagenManufacturerModels: Record<string, string[]> = {
  'Adria': ['Alpina', 'Alpina 663 HT', 'Alpina 763 HT', 'Alpina 903 HT', 'Adora', 'Adora 502 UL', 'Adora 522 UP', 'Adora 542 PT', 'Adora 573 PK', 'Adora 593 UP', 'Adora 613 UT', 'Adora 673 PK', 'Altea', 'Altea 362 LH', 'Altea 432 PX', 'Altea 472 LU', 'Altea 502 UL', 'Altea 552 PK', 'Altea PK 552', 'Altea 622 DP', 'Aviva', 'Aviva 360 DK', 'Aviva 400 DS', 'Aviva 470 PK', 'Aviva 502 UL', 'Aviva 540 UP', 'Aviva 563 PT', 'Aviva Lite', 'Action', 'Action 341 PH', 'Action 361 PH', 'Action 391 PH', 'Coral', 'Coral 590 DS', 'Coral 660 SL', 'Compact', 'Optima', 'Astella', 'Astella 644 DP', 'Astella 754 HP'],
  'Abbey': ['GTS', 'Vogue', 'Expression'],
  'Beachy': ['Strandwagen'],
  'Bürstner': ['Premio', 'Premio 380 TS', 'Premio 410 TS', 'Premio 425 TS', 'Premio 460 TS', 'Premio 466 Black Forest', 'Premio 495 TS', 'Premio 530 TS', 'Premio 540 TK', 'Premio Plus', 'Premio Plus 460 TS', 'Premio Plus 495 TS', 'Premio Plus 510 TK', 'Premio Plus 540 TK', 'Premio Life', 'Premio Life 460 TS', 'Premio Life 495 TS', 'Premio Life 510 TK', 'Averso', 'Averso 410 TS', 'Averso 460 TS', 'Averso 495 TK', 'Averso 510 TK', 'Averso Plus', 'Averso Plus 460 TS', 'Averso Plus 510 TK', 'Averso Harmony', 'Fun', 'Harmony Line', 'Belcanto', 'Amara', 'Smara', 'Flipper', 'Black Forest Edition', 'Season', 'Club'],
  'Cabby': ['Cailin', 'Comfort'],
  'Carado': ['Delight'],
  'Caretta': ['Mini-Caravan', 'Offroad'],
  'Dethleffs': ['Camper', 'Camper 470 ER', 'Camper 510 ER', 'Camper 530 FSK', 'Camper 550 ESK', 'Camper 560 FMK', 'Camper LiveStyle 560', 'Camper Lifestyle', 'Beduin', 'Beduin 510 ER', 'Beduin 540 QMK', 'Beduin 560 RHT', 'Beduin Scandinavia', 'c-go', 'c-go 465 FR', 'c-go 525 KR', 'c-go Up', 'c-go XL Family', 'c-joy', 'c-trend', 'c-trend I', 'Nomad', 'Nomad 470 ER', 'Nomad 510 ER', 'Nomad 540 QMK', 'Nomad 560 FMK', 'Exclusiv', 'Aero', 'Globetrotter', 'Generation', 'Advantage', 'Advantage 410 SK', 'Advantage 460 EL', 'Advantage 470 ER', 'Advantage 530 KR', 'Advantage 560 FMK', 'Advantage Edition', 'RM 5', '460 EL', '530 KR', '560 FMK'],
  'Eifelland': ['Holiday', 'Holiday 390', 'Holiday 540', 'Deseo', '390', 'EJ 360', 'EJ 390', 'EJ 460'],
  'Hennigsdorf': ['Aero', 'Aero Hennigsdorf', 'AHE 4', 'Bastei', 'Bastei BJ', 'QEK Junior'],
  'Polar': ['Original', 'Edition', '590 Original', '590 Edition', '620 Original', '620 Edition', '650 Original', '650 Edition', '720 Original', '720 Edition'],
  'Elddis': ['Affinity', 'Avante', 'Crusader'],
  'Eriba': ['Touring', 'Touring 310', 'Touring 410', 'Touring 470', 'Touring 530', 'Touring 540', 'Touring 550', 'Touring Troll', 'Touring Troll 530', 'Touring Troll 540', 'Touring Puck', 'Touring Puck L', 'Touring Pan', 'Touring Pan Famila', 'Touring Triton', 'Touring Triton 410', 'Touring Triton 420', 'Touring Familia', 'Troll', 'Troll 530', 'Troll 540', 'Puck', 'Puck L', 'Pan', 'Pan Famila', 'Triton', 'Triton 410', 'Triton 420', 'Titan', 'Faun', 'Car', 'Car 250', 'Novaline', 'Nova', 'Nova S', 'Nova SL', 'Nova GL', 'Nova Light', 'Feeling', 'Feeling 310', 'Feeling 425', 'Feeling 470', 'Exciting', 'Exciting 540', 'Living', 'Living 545'],
  'Fendt': ['Apero', 'Bianco', 'Bianco Activ', 'Bianco Activ 390 FH', 'Bianco Activ 465 SFB', 'Bianco Activ 495 SKM', 'Bianco Activ 515 SG', 'Bianco Activ 515 SGE', 'Bianco Activ 550 KMG', 'Bianco Selection', 'Bianco Sportive', 'Bianco Sportive 390 FHS', 'Bianco Sportive 390', 'Bianco Sportive 465 SFB', 'Bianco Sportive 465', 'Bianco Sportive 495 SKM', 'Bianco Sportive 495', 'Bianco Sportive 515 SG', 'Bianco Sportive 515', 'Bianco Sportive 550 KMG', 'Bianco Sportive 550', 'Bianco Sportive 560 SKM', 'Tendenza', 'Tendenza 465 SFB', 'Tendenza 465', 'Tendenza 495 SKM', 'Tendenza 495', 'Tendenza 515 SG', 'Tendenza 515', 'Tendenza 550 KMG', 'Tendenza 550', 'Tendenza Performance', 'Topas', 'Topas 495 TF', 'Topas 495', 'Topas 515 TF', 'Topas 515', 'Topas 550 TF', 'Topas 550', 'Topas 620 WGD', 'Opal', 'Opal 465 SFB', 'Opal 465', 'Opal 495 SKM', 'Opal 495', 'Opal 515 SG', 'Opal 515', 'Opal 550 KMG', 'Opal 550', 'Opal 560 SG', 'Opal 560 SGE', 'Diamant', 'Diamant 470 FH', 'Diamant 470', 'Diamant 515 SG', 'Diamant 515', 'Diamant 550 KMG', 'Diamant 550', 'Diamant 560 SD', 'Diamant 650 SFD', 'Saphir', 'Saphir 470 FH', 'Saphir 470', 'Saphir 490 SKF', 'Saphir 490', 'Saphir 490 KTM', 'Saphir 515 SG', 'Saphir 515', 'Saphir 560 SKM', 'Platin', 'Platin TFB', 'Platin TFB 650', 'Platin Sportiva', 'Brillant', 'Brillant 510 SKF', 'Brillant 510', 'Brillant 550 SF', 'Brillant 550', 'Larimar', 'Larimar 470 FH', 'Larimar 470', 'Larimar 515 SG', 'Larimar 515', 'Next', 'Vienna'],
  'Hobby': ['Beachy', 'Beachy 360', 'Beachy 400', 'Beachy 420', 'Beachy 450', 'OnTour', 'OnTour 390 SF', 'OnTour 460 DL', 'OnTour 470 KMF', 'OnTour 480 LU', 'OnTour 540 FU', 'OnTour Easy', 'OnTour XL', 'De Luxe', 'De Luxe 400 SB', 'De Luxe 440 SF', 'De Luxe 460 LU', 'De Luxe 460 UFe', 'De Luxe 490 KMF', 'De Luxe 540 FU', 'De Luxe 540 UL', 'De Luxe 545 KMF', 'De Luxe 560 CFe', 'De Luxe 560 KMFe', 'De Luxe 560 UL', 'De Luxe Easy', 'De Luxe Easy 400', 'De Luxe Easy 440', 'De Luxe Easy 460', 'De Luxe Easy 460 LU', 'De Luxe Easy 460 UFe', 'De Luxe Easy 540 UL', 'De Luxe Easy 560 CFe', 'De Luxe Edition', 'De Luxe Edition 540 UL', 'De Luxe Edition 560 UL', 'Excellent', 'Excellent Easy', 'Excellent Easy 400', 'Excellent Easy 440', 'Excellent Easy 460', 'Excellent Easy 540 UL', 'Excellent Easy 560 UL', 'Excellent Edition', 'Excellent 400 SB', 'Excellent 440 SF', 'Excellent 460 LU', 'Excellent 460 UFe', 'Excellent 495 UL', 'Excellent 540 FU', 'Excellent 540 KMFe', 'Excellent 540 LU', 'Excellent 540 UL', 'Excellent 540 WLU', 'Excellent 545 KMFe', 'Excellent 560 CFe', 'Excellent 560 KMFe', 'Excellent 560 LU', 'Excellent 560 UL', 'Excellent 560 WLU', 'Excellent 650 KMFe', 'Excellent 650 UFe', 'Excellent 720 UKFe', 'Prestige', 'Prestige 495 UL', 'Prestige 540 KMFe', 'Prestige 540 UL', 'Prestige 560 UL', 'Prestige 650 KMFe', 'Prestige 720 UKFe', 'Maxia', 'Maxia 540 UL', 'Maxia 560 LU', 'Maxia 585 KMF', 'Maxia 660 KMF', 'Maxia 660 WFU', 'Landhaus', 'Landhaus 770', 'Premium', 'Premium 495 UL', 'Premium 540 UL', 'Premium 560 UL', 'Premium 650 UMFe', 'Freistaat Edition', 'WFA', 'WFA 495', 'WFA 540', 'WFA 560', 'Classic', 'UHK 515', '400 SB', '460 LU', '540 FU', '540 UL', '560 UL', '650 KMFe'],
  'Hymer': ['Eriba Touring', 'Eriba Nova', 'Eriba Exciting', 'Eriba Feeling'],
  'Kabe': ['Royal', 'Imperial', 'Briljant', 'Hacienda', 'Ametist', 'Smaragd', 'Safir', 'Rubin', 'Onyx'],
  'Knaus': ['Sport', 'Sport 400 LK', 'Sport 460 EU', 'Sport 460 EU Silver Selection', 'Sport 500 KD', 'Sport 500 UF', 'Sport 540 FDK', 'Sport 540 UE', 'Sport 580 QS', 'Sport Silver Selection', 'Südwind', 'Südwind 420 QD', 'Südwind 460 EU', 'Südwind 500 EU', 'Südwind 500 PF', 'Südwind 500 UDF', 'Südwind 540 FDK', 'Südwind 540 UE', 'Südwind 580 QS', 'Südwind 590 UF', 'Südwind 650 PXB', 'Südwind Silver Selection', 'Südwind Black Selection', 'Starclass', 'Starclass 480', 'Starclass 500', 'Starclass 540', 'Starclass 595', 'Deseo', 'Deseo Plus', 'Deseo Transport', 'Travelino', 'Travelino 400 LK', 'Travelino 400 QD', 'YASEO', 'YASEO 460 EU', 'YASEO 500 KD', 'Eurostar', 'Eurostar 685', 'Azur'],
  'LMC': ['Musica', 'Musica 470 D', 'Musica 470 K', 'Musica 490 K', 'Musica 520 K', 'Musica 540 K', 'Sassino', 'Sassino 470 D', 'Sassino 480 K', 'Sassino 490 K', 'Style', 'Style 400 D', 'Style 470 E', 'Style 490 E', 'Style 510 K', 'Style 520 K', 'Style 530 K', 'Style 542 K', 'Style 580 K', 'Style 720 G', 'Style Lift', 'Vivo', 'Vivo 410 D', 'Vivo 470 K', 'Exquisite VIP', 'Dominant', 'Dominant 530 K', 'Dominant 540 D', 'Dominant 540 K', 'Dominant 640 HTE', 'Dominant 720 D', 'Münsterland', 'Münsterland 400 D', 'Münsterland 460 K', 'Maestro', 'Maestro 470 D', 'Maestro 490 K', 'Maestro 520 K'],
  'La Mancelle': ['Fantaisy', 'Liberty'],
  'Niewiadow': ['N126', 'N132', 'N-Line'],
  'Rapido': ['Caravan'],
  'Soma': ['Caravan'],
  'Sun Living': ['Caravan'],
  'Sunlight': ['Njoy', 'C-Klasse'],
  'Swift': ['Sprite', 'Challenger', 'Elegance', 'Conqueror'],
  'Sterckeman': ['Starlett', 'Starlett 390 PE', 'Starlett 420 CP', 'Starlett 470 CP', 'Starlett 490 PE', 'Starlett Comfort', 'Starlett First', 'Easy', 'Easy 370 CP', 'Easy 410 CP', 'Easy 450 CP', 'Easy 470 CP', 'Easy 495 CP', 'Easy 590 PE', 'Evolution', 'Evolution 390 CP', 'Evolution 470 PE', 'Alize', 'Alize 390 CP', 'Alize 420 CP', 'Alize 470 CE'],
  'Camppass': ['CR 400', 'CR 450', 'CR 455', 'CR 550', 'CR 550I', 'CR 555', 'CR 650'],
  'Caravelair': ['Allegra', 'Allegra 410', 'Allegra 426', 'Allegra 466', 'Allegra 470', 'Allegra 480', 'Allegra 486', 'Allegra 496', 'Antares', 'Antares 335', 'Antares 386', 'Antares 410', 'Antares 420', 'Antares 426', 'Antares 450', 'Antares 470', 'Antares 476', 'Antares 480', 'Antares 486', 'Antares 496', 'Alba', 'Alba 426', 'Alba 466', 'Artica', 'Artica 470', 'Artica 482', 'Artica 486', 'Antares Style', 'Antares Titanium'],
  'Tabbert': ['Rossini', 'Rossini 390', 'Rossini 450', 'Rossini 490', 'Rossini 540', 'Rossini 560', 'Da Vinci', 'Da Vinci 450', 'Da Vinci 490', 'Da Vinci 525', 'Da Vinci 540', 'Pep', 'Vivaldi', 'Vivaldi 490', 'Vivaldi 540', 'Puccini', 'Puccini 490', 'Puccini 550', 'Cellini', 'Cellini 750', 'Pantiga', 'Pantiga Finest Edition', 'Cazadora', 'Senara', 'Princesse', 'Princesse 495', 'Princesse 540', 'Princesse 560', 'Comtesse', 'Comtesse 495 HE', 'Comtesse 540 HE', 'Comtesse 560 HE', 'Baronesse', 'Condor'],
  'TEC': ['TravelKing', 'TravelKing 460K', 'TravelKing 490K', 'Traveler King', 'Traveler King 490K', 'Rotec', 'Rotec 510', 'Rotec 545', 'Travelbird', 'Freeway', 'Freetec', 'Freetec 600'],
  'Sprite': ['Alpine', 'Major', 'Mondial', 'Cruzer', 'Super Quattro', 'Coastline'],
  'Bailey': ['Unicorn', 'Alicanto Grande', 'Phoenix', 'Discovery', 'Pursuit', 'Pegasus'],
  'Trigano': ['Silver', 'Caravelair'],
  'Weinsberg': ['CaraOne', 'CaraOne 390 PUH', 'CaraOne 390 QD', 'CaraOne 400 LK', 'CaraOne 420 QD', 'CaraOne 450 FU', 'CaraOne 480 EU', 'CaraOne 480 QDK', 'CaraOne 500 FDK', 'CaraOne 500 QDK', 'CaraOne 540 EUH', 'CaraOne 540 UE', 'CaraOne 550 QDK', 'CaraOne 740 UDF', 'CaraOne Edition', 'CaraOne Edition Pepper', 'CaraTwo', 'CaraTwo 390 QD', 'CaraTwo 450 FU', 'CaraTwo 450 LK', 'CaraTwo 480 QDK', 'CaraCito', 'CaraCito 470 ED', 'CaraCito 600 SR'],
  'Wilk': ['Deluxe', 'Sento', 'Vida', 'Eterno', 'Safari', 'S3', 'S4', 'De Luxe', 'Stern', 'Sport'],
  'Wingamm': ['Caravan'],
  'T@B': ['320', '320 RS', '320 S', '400', '400 TD', '500', 'Combi', 'Vintage'],
  'Avento': ['Compact', 'Comfort', 'Excellent', 'Stylo'],
  'Bauer': ['Sonstiges Modell'],
  'Beyerland': ['Bel Air', 'Vitesse', 'Sprinter Caravan'],
  'Buccaneer': ['Cruiser', 'Galera', 'Schooner', 'Commodore'],
  'Chateau': ['Calista', 'La Car', 'Chiara', 'Caratt', 'Cantara'],
  'Cheltenham': ['Sable', 'Sapphire', 'Springbok'],
  'Compass': ['Camino', 'Capiro', 'Casita', 'Concerto', 'Camanoe'],
  'Conqueror': ['UEV-440', 'UEV-490', 'Commander'],
  'Coronet': ['Citrine'],
  'Eccles': ['Sport', 'Style', 'Citation'],
  'Erika': ['Sonstiges Modell'],
  'Fleurette': ['Magister', 'Discover', 'Wincester', 'Migrateur'],
  'Florium': ['Black Pearl', 'Mayflower', 'Wincester', 'Migrateur'],
  'GAZ': ['Sonstiges Modell'],
  'Hethon': ['BJ7', 'BJ8'],
  'Home-Car': ['Z-Line', 'A-Line', 'B-Line', 'X-Line'],
  'KIP': ['Vision', 'Vision XL', 'Eclipse'],
  'Knaus Tabbert': ['Sonstiges Modell'],
  'Lord Munsterland': ['Capitano', 'Tornado', 'Caprice'],
  'Lunar': ['Quasar', 'Cosmos', 'Clubman', 'Conquest'],
  'Mader': ['Camptourist', 'CT 6-2', 'Touring'],
  'Marquis': ['Aspire', 'Bessacarr', 'Major'],
  'Nordstar': ['Camp 4', 'Camp 6', 'Camp 8'],
  'Pendragon': ['Sonstiges Modell'],
  'Predom': ['Niewiadow', 'Tarpan', 'N126', 'N132'],
  'QEK': ['Junior', 'Aero'],
  'Sailler': ['Compact', 'Comfort'],
  'Sun Roller': ['Queen', 'Princess', 'Lord', 'King', 'Prince'],
  'TPV': ['Pickup', 'Caravan'],
  'Tudor': ['Sonstiges Modell'],
  'Andere': ['Sonstiges Modell']
};

// Sorted manufacturer list for Wohnwagen
export const wohnwagenManufacturers = Object.keys(wohnwagenManufacturerModels).sort();

// Body type options matching the motorhome_body_type enum
export const bodyTypes = [
  'Teilintegriert',
  'Alkoven',
  'Vollintegriert',
  'Kastenwagen',
  'Campingbus',
] as const;

// Wohnwagen body types
export const wohnwagenBodyTypes = [
  'Wohnwagen',
  'Faltcaravan',
  'Mobilheim',
] as const;

// Vehicle type options
export const vehicleTypes = [
  { value: 'Wohnmobil', label: 'Wohnmobil' },
  { value: 'Wohnwagen', label: 'Wohnwagen' },
] as const;

// Base vehicle / chassis options with typical engine power (PS) ranges
// PS depends on the chassis, not the Wohnmobil brand – this is the correct mapping
export interface BaseVehicleOption {
  label: string;
  powerOptions: number[]; // PS values (sorted ascending)
}

export const baseVehicles: BaseVehicleOption[] = [
  // Current Fiat Ducato (2014+ / 2020+ MultiJet3, 2.2L, incl. 2025 200PS top)
  { label: 'Fiat Ducato', powerOptions: [120, 140, 160, 180, 200] },
  // Older Ducato generations (2006-2014: 2.3L MultiJet / 3.0L MultiJet, + earlier)
  { label: 'Fiat Ducato (älter)', powerOptions: [100, 115, 120, 130, 140, 148, 150, 157, 160, 177, 178, 180] },
  // Mercedes Sprinter (W907/910 2018+: OM654 2.0L + OM642 3.0L V6, and older W906)
  { label: 'Mercedes Sprinter', powerOptions: [84, 95, 109, 114, 129, 143, 150, 163, 170, 177, 190] },
  // Mercedes Sprinter older W906 (2006-2018)
  { label: 'Mercedes Sprinter (älter)', powerOptions: [88, 95, 109, 129, 150, 163, 177, 190] },
  // Ford Transit (2014+ EcoBlue 2.0L, and older 2.2L TDCi, incl. 2024+ 200PS)
  { label: 'Ford Transit', powerOptions: [105, 125, 130, 140, 150, 155, 170, 185, 190, 200] },
  // VW Crafter (2017+ 2.0L TDI, shared platform with MAN TGE)
  { label: 'VW Crafter', powerOptions: [102, 122, 140, 163, 177] },
  // MAN TGE (2017+, identical to VW Crafter)
  { label: 'MAN TGE', powerOptions: [102, 122, 140, 163, 177] },
  // VW Crafter older (2006-2016, shared with Mercedes Sprinter W906)
  { label: 'VW Crafter (älter)', powerOptions: [109, 136, 163] },
  // Renault Master (2025+ NEW 2.0 dCi + 2019+ 2.3 dCi + 2010+ older)
  { label: 'Renault Master', powerOptions: [110, 115, 125, 130, 135, 145, 150, 170, 180] },
  // Citroën Jumper (Sevel-Platform = Ducato, same engines)
  { label: 'Citroën Jumper', powerOptions: [120, 140, 160, 180] },
  // Peugeot Boxer (Sevel-Platform = Ducato, same engines)
  { label: 'Peugeot Boxer', powerOptions: [120, 140, 160, 180] },
  // Iveco Daily (2014+ 2.3L / 3.0L F1C, various power stages, incl. older 90PS)
  { label: 'Iveco Daily', powerOptions: [90, 116, 120, 136, 140, 150, 156, 160, 170, 180, 205, 210] },
  // VW T5 (2003-2015, 2.0 TDI / 2.5 TDI)
  { label: 'VW T5', powerOptions: [84, 86, 102, 114, 131, 140, 174, 180] },
  // VW T6 / T6.1 (2015-2024, 2.0 TDI / 2.0 TSI, incl. 84PS base)
  { label: 'VW T6 / T6.1', powerOptions: [84, 90, 110, 150, 199, 204] },
  // VW T7 Multivan (2021+, 1.4/1.5 eHybrid + 2.0 TDI/TSI)
  { label: 'VW T7 Multivan', powerOptions: [136, 150, 204, 218, 245] },
  // Mercedes Vito / V-Klasse (W447 2014+, OM654/OM651)
  { label: 'Mercedes Vito / V-Klasse', powerOptions: [102, 116, 136, 150, 163, 190, 211, 239] },
  // Mercedes Marco Polo (based on V-Klasse)
  { label: 'Mercedes Marco Polo', powerOptions: [136, 163, 190, 239] },
  // Opel Vivaro / Zafira Life (2019+, 1.5/2.0 CDTI)
  { label: 'Opel Vivaro / Zafira Life', powerOptions: [102, 120, 145, 150, 177] },
  // Toyota Proace / Proace Verso (2016+, PSA engines)
  { label: 'Toyota Proace', powerOptions: [102, 120, 145, 150, 177] },
  // Citroën SpaceTourer / Jumpy
  { label: 'Citroën SpaceTourer', powerOptions: [102, 120, 145, 150, 177] },
  // Peugeot Traveller / Expert
  { label: 'Peugeot Traveller', powerOptions: [102, 120, 145, 150, 177] },
  // Nissan NV400 (rebadged Renault Master, same engines)
  { label: 'Nissan NV400', powerOptions: [110, 125, 135, 145, 150, 170] },
  // Opel Movano (2010+ = Renault Master, 2025+ NEW)
  { label: 'Opel Movano', powerOptions: [110, 125, 135, 145, 150, 170, 180] },
  // Ford Custom / Tourneo Custom (2.0 EcoBlue)
  { label: 'Ford Transit Custom', powerOptions: [105, 130, 150, 170, 185] },
  // Fiat E-Ducato (electric, 2022+)
  { label: 'Fiat E-Ducato', powerOptions: [122, 272] },
  // Mercedes eSprinter (electric, 2024+)
  { label: 'Mercedes eSprinter', powerOptions: [136, 204] },
  // Renault Trafic (2014+, 2.0 dCi)
  { label: 'Renault Trafic', powerOptions: [110, 120, 130, 150, 170] },
  // Hyundai Staria (2022+, 2.2 CRDi, used by Crosscamp etc.)
  { label: 'Hyundai Staria', powerOptions: [177] },
  // Maxus Deliver 9 / eDeliver 9 (Chinese import, growing in EU)
  { label: 'Maxus Deliver 9', powerOptions: [136, 150] },
  { label: 'Maxus eDeliver 9', powerOptions: [136, 204] },
  // AL-KO / SAF Chassis (used for large motorhomes, PS varies by cab)
  { label: 'AL-KO Chassis', powerOptions: [] },
  // Hymer-eigenes Chassis (SLC)
  { label: 'SLC Chassis (Hymer)', powerOptions: [] },
  { label: 'Sonstige', powerOptions: [] },
];

export const baseVehicleLabels = baseVehicles.map(bv => bv.label);

// Convert PS to kW
export function psToKw(ps: number): number {
  return Math.round(ps * 0.7355);
}

// Format power as "XXkW/YYYPS" for display
export function formatPower(ps: number): string {
  return `${psToKw(ps)}kW/${ps}PS`;
}

// Get power options for a specific base vehicle
export function getPowerOptionsForBaseVehicle(baseVehicle: string): number[] {
  const found = baseVehicles.find(bv => bv.label === baseVehicle);
  return found?.powerOptions ?? [];
}

// Manufacturer alias map for common misspellings and variants
export const manufacturerAliases: Record<string, string> = {
  'Vw': 'Volkswagen',
  'VW': 'Volkswagen',
  'vw': 'Volkswagen',
  'volkswagen': 'Volkswagen',
  'Mercedes': 'Mercedes-Benz',
  'Benz': 'Mercedes-Benz',
  'mercedes': 'Mercedes-Benz',
  'mercedes benz': 'Mercedes-Benz',
  'CI': 'CI International',
  'ci': 'CI International',
  'Hymer-Eriba': 'Eriba',
  'Roller-Team': 'Roller Team',
  'roller team': 'Roller Team',
  'Ahorn Camp': 'Ahorn',
  'ahorn camp': 'Ahorn',
  'Sunligth': 'Sunlight',
  'sunligth': 'Sunlight',
  'sunlight': 'Sunlight',
  'Hymrr': 'Hymer',
  'hymer': 'Hymer',
  'Mooevo': 'Mooveo',
  'mooevo': 'Mooveo',
  'Xgo': 'XGO',
  'xgo': 'XGO',
  'Poessl': 'Pössl',
  'Possl': 'Pössl',
  'pössl': 'Pössl',
  'possl': 'Pössl',
  'poessl': 'Pössl',
  'Buerstner': 'Bürstner',
  'Burstner': 'Bürstner',
  'bürstner': 'Bürstner',
  'burstner': 'Bürstner',
  'buerstner': 'Bürstner',
  'Gluecksmobil': 'Glücksmobil',
  'Niesmann Bischoff': 'Niesmann+Bischoff',
  'Niesmann-Bischoff': 'Niesmann+Bischoff',
  'Niesmann': 'Niesmann+Bischoff',
  'niesmann': 'Niesmann+Bischoff',
  'Bresler': 'Bresler Mobile',
  'Bresler Mobil': 'Bresler Mobile',
  'Schwaben Mobil': 'Schwabenmobil',
  'Schwaben-Mobil': 'Schwabenmobil',
  'CS': 'CS Reisemobile',
  'cs': 'CS Reisemobile',
  'Karmann-Mobil': 'Karmann',
  'Karmann Mobil': 'Karmann',
  'la strada': 'La Strada',
  'LaStrada': 'La Strada',
  'Etrusko': 'Etrusco',
  'etrusko': 'Etrusco',
  'etrusco': 'Etrusco',
  'Peugot': 'Peugeot',
  'peugeot': 'Peugeot',
  'PEUGEOT': 'Peugeot',
  'nissan': 'Nissan',
  'NISSAN': 'Nissan',
  'Citroen': 'Citroën',
  'citroen': 'Citroën',
  'citroën': 'Citroën',
  'CITROEN': 'Citroën',
  'opel': 'Opel',
  'OPEL': 'Opel',
  'Fiat Ducato': 'Fiat',
  'fiat ducato': 'Fiat',
  'Fiat': 'Fiat',
  'fiat': 'Fiat',
  'Fiat ': 'Fiat',
  'ford': 'Ford',
  'Ford Transit': 'Ford',
  'Ford-Transit': 'Ford',
  'Iveco Daily': 'Iveco',
  'Iveco': 'Iveco',
  'iveco': 'Iveco',
  'IVECO': 'Iveco',
  'Renault': 'Renault',
  'renault': 'Renault',
  'Renault Master': 'Renault',
  'Renault Trafic': 'Renault',
  'Toyota': 'Toyota',
  'toyota': 'Toyota',
  'TOYOTA': 'Toyota',
  'Hyundai': 'Hyundai',
  'hyundai': 'Hyundai',
  'HYUNDAI': 'Hyundai',
  'LMC ': 'LMC',
  'Giottoline': 'GiottiLine',
  'giottoline': 'GiottiLine',
  'Giotti Line': 'GiottiLine',
  'giotti line': 'GiottiLine',
  'weinsberg': 'Weinsberg',
  'fendt': 'Fendt',
  'hobby': 'Hobby',
  'dethleffs': 'Dethleffs',
  'adria': 'Adria',
  'knaus': 'Knaus',
  'carado': 'Carado',
  'carthago': 'Carthago',
  'chausson': 'Chausson',
  'frankia': 'Frankia',
  'forster': 'Forster',
  'pilote': 'Pilote',
  'rapido': 'Rapido',
  'tabbert': 'Tabbert',
  'concorde': 'Concorde',
  'laika': 'Laika',
  'malibu': 'Malibu',
  'morelo': 'Morelo',
  'Hehn': 'Hehn Mobil',
  'hehn': 'Hehn Mobil',
  'hehn mobil': 'Hehn Mobil',
  'Forest': 'Forest River',
  'forest': 'Forest River',
  'forest river': 'Forest River',
  'Carado T447': 'Carado',
  'carado t447': 'Carado',
  'Etrusko 6.6 sf': 'Etrusco',
  'Hymer Eriba': 'Eriba',
  'hymer eriba': 'Eriba',
  'HymerEriba': 'Eriba',
  'Eriba Hymer': 'Eriba',
  'Hennigsdorf': 'Hennigsdorf',
  'hennigsdorf': 'Hennigsdorf',
  'Hennigsdorf ': 'Hennigsdorf',
  'Polar': 'Polar',
  'polar': 'Polar',
  'Tabbert ': 'Tabbert',
  'BÃ¼rstner': 'Bürstner',
  'BÃ¼rstner ': 'Bürstner',
  'PÃ¶ssl': 'Pössl',
  'SÃ¼dwind': 'Südwind',
  'Concord': 'Pössl',
  'Concord-Compact': 'Pössl',
  'Sun Living': 'Sun Living',
  'sun living': 'Sun Living',
  'Sunliving': 'Sun Living',
  'sunliving': 'Sun Living',
  'Sun-Living': 'Sun Living',
  'Forest River': 'Forest River',
  'Forest-River': 'Forest River',
  'forest-river': 'Forest River',
  'ForestRiver': 'Forest River',
  'Niewiadow': 'Niewiadow',
  'niewiadow': 'Niewiadow',
  'Roller Team': 'Roller Team',
  'rollerteam': 'Roller Team',
  'RollerTeam': 'Roller Team',
  'Hymer-Eriba ': 'Eriba',
  'Sun Living ': 'Sun Living',
  'Mercedes Benz': 'Mercedes-Benz',
  'mercedes-benz': 'Mercedes-Benz',
  'MercedesBenz': 'Mercedes-Benz',
  'Sterckmann': 'Sterckeman',
  'Sterckman': 'Sterckeman',
  'sterckeman': 'Sterckeman',
  'Knaus Tabbert': 'Knaus',
  'KnausTabbert': 'Knaus',
  'Sun-Living S': 'Sun Living',
  'Caravelair': 'Caravelair',
  'caravelair': 'Caravelair',
  'Sun Roller': 'Roller Team',
  'Sun roller': 'Roller Team',
  'Eifelland': 'Eifelland',
  'eifelland': 'Eifelland',
  'Bischoff': 'Niesmann+Bischoff',
  'Eura': 'Eura Mobil',
  'EuraMobil': 'Eura Mobil',
  'Euramobil': 'Eura Mobil',
  'eura mobil': 'Eura Mobil',
  'eura-mobil': 'Eura Mobil',
  'Eriba Hymer ': 'Eriba',
  'Knausa': 'Knaus',
  'Roadcar': 'Roadcar',
  'roadcar': 'Roadcar',
  'Vario Mobil': 'VARIO mobil',
  'vario mobil': 'VARIO mobil',
  'VarioMobil': 'VARIO mobil',
  'Le Voyageur': 'Le Voyageur',
  'le voyageur': 'Le Voyageur',
  'LeVoyageur': 'Le Voyageur',
};

// Resolve a manufacturer name, applying alias and trimming (case-sensitive first, then case-insensitive)
export function resolveManufacturer(input: string): string {
  const trimmed = input.trim();
  if (manufacturerAliases[trimmed]) return manufacturerAliases[trimmed];
  const lower = trimmed.toLowerCase();
  for (const [key, val] of Object.entries(manufacturerAliases)) {
    if (key.toLowerCase() === lower) return val;
  }
  return trimmed;
}
