import {
  ArrowDownToLine,
  Baby,
  Building,
  Building2,
  Calendar,
  CalendarClock,
  CalendarDays,
  CircleDot,
  Clock,
  Coffee,
  Columns2,
  CookingPot,
  Copy,
  DoorClosed,
  DoorOpen,
  Droplets,
  Expand,
  Eye,
  EyeOff,
  Flame,
  HeartHandshake,
  Heater,
  HelpCircle,
  Home,
  Key,
  Maximize2,
  MessageCircle,
  MessagesSquare,
  Microwave,
  Minimize2,
  PartyPopper,
  PencilRuler,
  Recycle,
  RefreshCw,
  Refrigerator,
  Ruler,
  Snowflake,
  Sofa,
  Sparkles,
  Square,
  Timer,
  Truck,
  User,
  UserCog,
  Users,
  Wind,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { UNSURE } from "@/features/funnel-a/catalog";
import type { ChoiceField, ExtraApplianceId } from "@/features/funnel-a/steps";

/** Icons je Antwortfeld und Katalog-ID; „unsicher“ fällt auf HelpCircle zurück. */
const CHOICE_ICONS: Partial<Record<ChoiceField, Record<string, LucideIcon>>> = {
  kitchen_form: { [UNSURE]: MessagesSquare },
  room_type: { offen: Sofa, geschlossen: DoorClosed, halboffen: DoorOpen, planung: PencilRuler },
  kitchen_size: { klein: Minimize2, mittel: Square, gross: Maximize2, xl: Expand, [UNSURE]: Ruler },
  kitchen_style: { [UNSURE]: MessagesSquare },
  cooktop_type: { induktion: Zap, kochfeldabzug: Wind, ceran: CircleDot, gas: Flame },
  oven_placement: { "unter-kochfeld": ArrowDownToLine, augenhoehe: Eye, doppelt: Copy },
  cooling: { einbau: Refrigerator, kombi: Snowflake, side_by_side: Columns2, vorhanden: Recycle },
  cooking_style: { allein: User, paar: Users, familie: Baby, freunde: PartyPopper, selten: Timer },
  purchase_reason: { neukauf: Sparkles, renovierung: RefreshCw, umzug: Truck, modernisierung: Wrench },
  housing: { rent_apartment: Building2, rent_house: Home, own_apartment: Building, own_house: Key, [UNSURE]: EyeOff },
  decision_maker: { allein: User, gemeinsam: HeartHandshake, andere: UserCog },
  timeframe: {
    asap: Zap,
    "1-3": Calendar,
    "4-6": CalendarDays,
    "7-12": CalendarClock,
    spaeter: Clock,
    beratung: MessageCircle,
  },
};

export function choiceIcon(field: ChoiceField, id: string): LucideIcon | undefined {
  return CHOICE_ICONS[field]?.[id] ?? (id === UNSURE ? HelpCircle : undefined);
}

export const EXTRA_APPLIANCE_ICONS: Partial<Record<ExtraApplianceId, LucideIcon>> = {
  geschirrspueler: Droplets,
  mikrowelle: Microwave,
  dampfgarer: CookingPot,
  kaffee: Coffee,
  weinkuehler: Wine,
  waermeschublade: Heater,
};
