// AUTO-GENERATED by scripts/generate-ratgeber-meta.mjs – do not hand-edit.
// Total entries: 88.
// This file is intentionally tiny so it can be loaded eagerly. The full
// RatgeberConfig (sections + faqItems) lives in ratgeber-<group>.ts and
// is loaded on demand via loadRatgeberConfig() in ratgeber-index.ts.

export interface RatgeberMeta {
  slug: string;
  path: string;
  h1: string;
  metaDescription: string;
  category: "brand" | "condition";
  brandName?: string;
  /** Filename (without extension) of the data file that owns the full config. */
  dataFile: string;
}

export const ratgeberMeta: RatgeberMeta[] = [
  {
    "slug": "adria-wohnmobil-verkaufen",
    "path": "/ratgeber/adria-wohnmobil-verkaufen",
    "h1": "Adria Wohnmobil verkaufen",
    "metaDescription": "Adria Wohnmobil verkaufen zum Bestpreis. Ob Coral, Matrix oder Twin — erfahren Sie, wie Sie den maximalen Erlös für Ihren Adria erzielen.",
    "category": "brand",
    "brandName": "Adria",
    "dataFile": "ratgeber-adria"
  },
  {
    "slug": "adria-wohnmobil-versteigern",
    "path": "/ratgeber/adria-wohnmobil-versteigern",
    "h1": "Adria Wohnmobil versteigern",
    "metaDescription": "Adria Wohnmobil versteigern und durch Bieterwettbewerb den besten Preis erzielen. Sicher mit Mindestgebot bei CaravanWert.",
    "category": "brand",
    "brandName": "Adria",
    "dataFile": "ratgeber-adria"
  },
  {
    "slug": "adria-wohnmobil-wert-ermitteln",
    "path": "/ratgeber/adria-wohnmobil-wert-ermitteln",
    "h1": "Wert Ihres Adria Wohnmobils ermitteln",
    "metaDescription": "Ermitteln Sie den aktuellen Marktwert Ihres Adria Wohnmobils. Professionelle Bewertung für Coral, Matrix, Twin und Sonic — kostenlos in 24 Stunden.",
    "category": "brand",
    "brandName": "Adria",
    "dataFile": "ratgeber-adria"
  },
  {
    "slug": "buerstner-wohnmobil-verkaufen",
    "path": "/ratgeber/buerstner-wohnmobil-verkaufen",
    "h1": "Bürstner Wohnmobil verkaufen",
    "metaDescription": "Bürstner Wohnmobil verkaufen zum Top-Preis. Ob Lyseo, Ixeo oder Elegance — wir zeigen Ihnen, wie Sie den maximalen Erlös für Ihren Bürstner erzielen.",
    "category": "brand",
    "brandName": "Bürstner",
    "dataFile": "ratgeber-buerstner"
  },
  {
    "slug": "buerstner-wohnmobil-versteigern",
    "path": "/ratgeber/buerstner-wohnmobil-versteigern",
    "h1": "Bürstner Wohnmobil versteigern",
    "metaDescription": "Bürstner Wohnmobil versteigern und durch Bieterwettbewerb den besten Preis erzielen. Sicher mit Mindestgebot bei CaravanWert.",
    "category": "brand",
    "brandName": "Bürstner",
    "dataFile": "ratgeber-buerstner"
  },
  {
    "slug": "buerstner-wohnmobil-wert-ermitteln",
    "path": "/ratgeber/buerstner-wohnmobil-wert-ermitteln",
    "h1": "Wert Ihres Bürstner Wohnmobils ermitteln",
    "metaDescription": "Ermitteln Sie den aktuellen Marktwert Ihres Bürstner Wohnmobils. Professionelle Bewertung für Lyseo, Ixeo, Elegance und Campeo — kostenlos.",
    "category": "brand",
    "brandName": "Bürstner",
    "dataFile": "ratgeber-buerstner"
  },
  {
    "slug": "carado-wohnmobil-verkaufen",
    "path": "/ratgeber/carado-wohnmobil-verkaufen",
    "h1": "Carado Wohnmobil verkaufen",
    "metaDescription": "Carado Wohnmobil verkaufen zum Bestpreis. Ob T-Modell, I-Modell oder Vlow — erfahren Sie, wie Sie den maximalen Erlös für Ihren Carado erzielen.",
    "category": "brand",
    "brandName": "Carado",
    "dataFile": "ratgeber-carado"
  },
  {
    "slug": "carado-wohnmobil-versteigern",
    "path": "/ratgeber/carado-wohnmobil-versteigern",
    "h1": "Carado Wohnmobil versteigern",
    "metaDescription": "Carado Wohnmobil versteigern und durch Bieterwettbewerb den besten Preis erzielen. Sicher mit Mindestgebot bei CaravanWert.",
    "category": "brand",
    "brandName": "Carado",
    "dataFile": "ratgeber-carado"
  },
  {
    "slug": "carado-wohnmobil-wert-ermitteln",
    "path": "/ratgeber/carado-wohnmobil-wert-ermitteln",
    "h1": "Wert Ihres Carado Wohnmobils ermitteln",
    "metaDescription": "Ermitteln Sie den aktuellen Marktwert Ihres Carado Wohnmobils. Professionelle Bewertung für T-, I-, A-Modelle und Vlow — kostenlos.",
    "category": "brand",
    "brandName": "Carado",
    "dataFile": "ratgeber-carado"
  },
  {
    "slug": "carthago-wohnmobil-verkaufen",
    "path": "/ratgeber/carthago-wohnmobil-verkaufen",
    "h1": "Carthago Wohnmobil verkaufen",
    "metaDescription": "Carthago Wohnmobil verkaufen zum Premiumpreis. Ob Chic C-Line, Liner oder C-Tourer — erfahren Sie, wie Sie den maximalen Erlös für Ihren Carthago erzielen.",
    "category": "brand",
    "brandName": "Carthago",
    "dataFile": "ratgeber-carthago"
  },
  {
    "slug": "carthago-wohnmobil-versteigern",
    "path": "/ratgeber/carthago-wohnmobil-versteigern",
    "h1": "Carthago Wohnmobil versteigern",
    "metaDescription": "Carthago Wohnmobil versteigern und Premiumpreise durch Bieterwettbewerb erzielen. Sicher mit Mindestgebot. Qualifizierte Bieter bei CaravanWert.",
    "category": "brand",
    "brandName": "Carthago",
    "dataFile": "ratgeber-carthago"
  },
  {
    "slug": "carthago-wohnmobil-wert-ermitteln",
    "path": "/ratgeber/carthago-wohnmobil-wert-ermitteln",
    "h1": "Wert Ihres Carthago Wohnmobils ermitteln",
    "metaDescription": "Ermitteln Sie den Premiumwert Ihres Carthago Wohnmobils. Spezialisierte Bewertung für Chic C-Line, E-Line, C-Tourer und Liner — kostenlos.",
    "category": "brand",
    "brandName": "Carthago",
    "dataFile": "ratgeber-carthago"
  },
  {
    "slug": "chausson-wohnmobil-verkaufen",
    "path": "/ratgeber/chausson-wohnmobil-verkaufen",
    "h1": "Chausson Wohnmobil verkaufen",
    "metaDescription": "Chausson Wohnmobil verkaufen zum Bestpreis. Ob Titanium, Welcome oder Flash — erfahren Sie, wie Sie den maximalen Erlös erzielen.",
    "category": "brand",
    "brandName": "Chausson",
    "dataFile": "ratgeber-chausson"
  },
  {
    "slug": "chausson-wohnmobil-versteigern",
    "path": "/ratgeber/chausson-wohnmobil-versteigern",
    "h1": "Chausson Wohnmobil versteigern",
    "metaDescription": "Chausson Wohnmobil versteigern und durch Bieterwettbewerb den besten Preis erzielen. Ford-Basis-Modelle besonders gefragt.",
    "category": "brand",
    "brandName": "Chausson",
    "dataFile": "ratgeber-chausson"
  },
  {
    "slug": "chausson-wohnmobil-wert-ermitteln",
    "path": "/ratgeber/chausson-wohnmobil-wert-ermitteln",
    "h1": "Wert Ihres Chausson Wohnmobils ermitteln",
    "metaDescription": "Ermitteln Sie den aktuellen Marktwert Ihres Chausson Wohnmobils. Bewertung für Titanium, Welcome, Flash und X — kostenlos in 24 Stunden.",
    "category": "brand",
    "brandName": "Chausson",
    "dataFile": "ratgeber-chausson"
  },
  {
    "slug": "concorde-wohnmobil-verkaufen",
    "path": "/ratgeber/concorde-wohnmobil-verkaufen",
    "h1": "Concorde Wohnmobil verkaufen",
    "metaDescription": "Concorde Wohnmobil verkaufen zum Top-Preis. Ob Liner, Carver oder Charisma — erfahren Sie, wie Sie den maximalen Erlös für Ihr Luxus-Reisemobil erzielen.",
    "category": "brand",
    "brandName": "Concorde",
    "dataFile": "ratgeber-concorde"
  },
  {
    "slug": "concorde-wohnmobil-versteigern",
    "path": "/ratgeber/concorde-wohnmobil-versteigern",
    "h1": "Concorde Wohnmobil versteigern",
    "metaDescription": "Concorde Wohnmobil versteigern und durch Bieterwettbewerb unter zahlungskräftigen Käufern den Luxus-Preis erzielen.",
    "category": "brand",
    "brandName": "Concorde",
    "dataFile": "ratgeber-concorde"
  },
  {
    "slug": "concorde-wohnmobil-wert-ermitteln",
    "path": "/ratgeber/concorde-wohnmobil-wert-ermitteln",
    "h1": "Wert Ihres Concorde Wohnmobils ermitteln",
    "metaDescription": "Ermitteln Sie den aktuellen Marktwert Ihres Concorde Wohnmobils. Individuelle Luxus-Bewertung für Liner, Carver, Charisma und Credo — kostenlos.",
    "category": "brand",
    "brandName": "Concorde",
    "dataFile": "ratgeber-concorde"
  },
  {
    "slug": "dethleffs-wohnmobil-verkaufen",
    "path": "/ratgeber/dethleffs-wohnmobil-verkaufen",
    "h1": "Dethleffs Wohnmobil verkaufen",
    "metaDescription": "Dethleffs Wohnmobil verkaufen zum Bestpreis. Ob Globebus, Esprit oder Pulse — wir zeigen Ihnen, wie Sie den maximalen Erlös erzielen. Kostenlose Bewertung.",
    "category": "brand",
    "brandName": "Dethleffs",
    "dataFile": "ratgeber-dethleffs"
  },
  {
    "slug": "dethleffs-wohnmobil-versteigern",
    "path": "/ratgeber/dethleffs-wohnmobil-versteigern",
    "h1": "Dethleffs Wohnmobil versteigern",
    "metaDescription": "Dethleffs Wohnmobil versteigern und den Marktpreis durch Wettbewerb maximieren. Sicher mit Mindestgebot. Transparent und professionell bei CaravanWert.",
    "category": "brand",
    "brandName": "Dethleffs",
    "dataFile": "ratgeber-dethleffs"
  },
  {
    "slug": "dethleffs-wohnmobil-wert-ermitteln",
    "path": "/ratgeber/dethleffs-wohnmobil-wert-ermitteln",
    "h1": "Wert Ihres Dethleffs Wohnmobils ermitteln",
    "metaDescription": "Ermitteln Sie den aktuellen Marktwert Ihres Dethleffs Wohnmobils. Professionelle Bewertung für Globebus, Esprit, Pulse und Alpa — kostenlos und unverbindlich.",
    "category": "brand",
    "brandName": "Dethleffs",
    "dataFile": "ratgeber-dethleffs"
  },
  {
    "slug": "hobby-wohnmobil-verkaufen",
    "path": "/ratgeber/hobby-wohnmobil-verkaufen",
    "h1": "Hobby Wohnmobil verkaufen",
    "metaDescription": "Hobby Wohnmobil verkaufen zum Top-Preis. Ob Optima, Siesta oder De Luxe — erfahren Sie, wie Sie den maximalen Erlös für Ihren Hobby erzielen.",
    "category": "brand",
    "brandName": "Hobby",
    "dataFile": "ratgeber-hobby"
  },
  {
    "slug": "hobby-wohnmobil-versteigern",
    "path": "/ratgeber/hobby-wohnmobil-versteigern",
    "h1": "Hobby Wohnmobil versteigern",
    "metaDescription": "Hobby Wohnmobil versteigern und durch Bieterwettbewerb den besten Preis erzielen. Sicher mit Mindestgebot bei CaravanWert.",
    "category": "brand",
    "brandName": "Hobby",
    "dataFile": "ratgeber-hobby"
  },
  {
    "slug": "hobby-wohnmobil-wert-ermitteln",
    "path": "/ratgeber/hobby-wohnmobil-wert-ermitteln",
    "h1": "Wert Ihres Hobby Wohnmobils ermitteln",
    "metaDescription": "Ermitteln Sie den aktuellen Marktwert Ihres Hobby Wohnmobils. Professionelle Bewertung für Optima, Siesta, Vantana und De Luxe — kostenlos.",
    "category": "brand",
    "brandName": "Hobby",
    "dataFile": "ratgeber-hobby"
  },
  {
    "slug": "hymer-wohnmobil-verkaufen",
    "path": "/ratgeber/hymer-wohnmobil-verkaufen",
    "h1": "Hymer Wohnmobil verkaufen",
    "metaDescription": "Hymer Wohnmobil verkaufen zum Bestpreis. Ob B-Klasse, Exsis oder ML-T — erzielen Sie den maximalen Erlös. Kostenlose Bewertung in 24h.",
    "category": "brand",
    "brandName": "Hymer",
    "dataFile": "ratgeber-hymer"
  },
  {
    "slug": "hymer-wohnmobil-versteigern",
    "path": "/ratgeber/hymer-wohnmobil-versteigern",
    "h1": "Hymer Wohnmobil versteigern",
    "metaDescription": "Hymer Wohnmobil versteigern mit Mindestgebot. Erzielen Sie durch die Auktion einen Top-Preis für Ihre B-Klasse, Exsis oder ML-T. Transparent und sicher.",
    "category": "brand",
    "brandName": "Hymer",
    "dataFile": "ratgeber-hymer"
  },
  {
    "slug": "hymer-wohnmobil-wert-ermitteln",
    "path": "/ratgeber/hymer-wohnmobil-wert-ermitteln",
    "h1": "Wert Ihres Hymer Wohnmobils ermitteln",
    "metaDescription": "Aktuellen Marktwert Ihres Hymer Wohnmobils ermitteln. Professionelle Bewertung mit Echtzeit-Marktdaten für B-Klasse, Exsis und ML-T.",
    "category": "brand",
    "brandName": "Hymer",
    "dataFile": "ratgeber-hymer"
  },
  {
    "slug": "knaus-wohnmobil-verkaufen",
    "path": "/ratgeber/knaus-wohnmobil-verkaufen",
    "h1": "Knaus Wohnmobil verkaufen",
    "metaDescription": "Knaus Wohnmobil verkaufen zum Top-Preis. Ob Sun TI, Sky Wave oder Van TI — erfahren Sie, wie Sie den maximalen Erlös für Ihren Knaus erzielen.",
    "category": "brand",
    "brandName": "Knaus",
    "dataFile": "ratgeber-knaus"
  },
  {
    "slug": "knaus-wohnmobil-versteigern",
    "path": "/ratgeber/knaus-wohnmobil-versteigern",
    "h1": "Knaus Wohnmobil versteigern",
    "metaDescription": "Knaus Wohnmobil versteigern und durch Bieterwettbewerb den besten Preis erzielen. Sicher mit Mindestgebot bei CaravanWert.",
    "category": "brand",
    "brandName": "Knaus",
    "dataFile": "ratgeber-knaus"
  },
  {
    "slug": "knaus-wohnmobil-wert-ermitteln",
    "path": "/ratgeber/knaus-wohnmobil-wert-ermitteln",
    "h1": "Wert Ihres Knaus Wohnmobils ermitteln",
    "metaDescription": "Ermitteln Sie den aktuellen Marktwert Ihres Knaus Wohnmobils. Professionelle Bewertung für Sun TI, Sky Wave, Van TI und BoxStar — kostenlos.",
    "category": "brand",
    "brandName": "Knaus",
    "dataFile": "ratgeber-knaus"
  },
  {
    "slug": "laika-wohnmobil-verkaufen",
    "path": "/ratgeber/laika-wohnmobil-verkaufen",
    "h1": "Laika Wohnmobil verkaufen",
    "metaDescription": "Laika Wohnmobil verkaufen zum Bestpreis. Ob Ecovip, Kreos oder Kosmo — erfahren Sie, wie Sie den maximalen Erlös für Ihr italienisches Reisemobil erzielen.",
    "category": "brand",
    "brandName": "Laika",
    "dataFile": "ratgeber-laika"
  },
  {
    "slug": "laika-wohnmobil-versteigern",
    "path": "/ratgeber/laika-wohnmobil-versteigern",
    "h1": "Laika Wohnmobil versteigern",
    "metaDescription": "Laika Wohnmobil versteigern und durch Bieterwettbewerb den besten Preis erzielen. Ecovip und Kreos besonders gefragt.",
    "category": "brand",
    "brandName": "Laika",
    "dataFile": "ratgeber-laika"
  },
  {
    "slug": "laika-wohnmobil-wert-ermitteln",
    "path": "/ratgeber/laika-wohnmobil-wert-ermitteln",
    "h1": "Wert Ihres Laika Wohnmobils ermitteln",
    "metaDescription": "Ermitteln Sie den aktuellen Marktwert Ihres Laika Wohnmobils. Bewertung für Ecovip, Kreos, Kosmo und Ecovip H — kostenlos in 24 Stunden.",
    "category": "brand",
    "brandName": "Laika",
    "dataFile": "ratgeber-laika"
  },
  {
    "slug": "poessl-wohnmobil-verkaufen",
    "path": "/ratgeber/poessl-wohnmobil-verkaufen",
    "h1": "Pössl Wohnmobil verkaufen",
    "metaDescription": "Pössl Wohnmobil verkaufen zum Top-Preis. Ob Summit, Roadcamp oder Campster — erfahren Sie, wie Sie den maximalen Erlös für Ihren Pössl erzielen.",
    "category": "brand",
    "brandName": "Pössl",
    "dataFile": "ratgeber-poessl"
  },
  {
    "slug": "poessl-wohnmobil-versteigern",
    "path": "/ratgeber/poessl-wohnmobil-versteigern",
    "h1": "Pössl Wohnmobil versteigern",
    "metaDescription": "Pössl Kastenwagen versteigern und durch Bieterwettbewerb den besten Preis erzielen. Sicher mit Mindestgebot bei CaravanWert.",
    "category": "brand",
    "brandName": "Pössl",
    "dataFile": "ratgeber-poessl"
  },
  {
    "slug": "poessl-wohnmobil-wert-ermitteln",
    "path": "/ratgeber/poessl-wohnmobil-wert-ermitteln",
    "h1": "Wert Ihres Pössl Wohnmobils ermitteln",
    "metaDescription": "Ermitteln Sie den aktuellen Marktwert Ihres Pössl Kastenwagens. Bewertung für Summit, Roadcamp, Campster und Vanster — kostenlos in 24 Stunden.",
    "category": "brand",
    "brandName": "Pössl",
    "dataFile": "ratgeber-poessl"
  },
  {
    "slug": "rapido-wohnmobil-verkaufen",
    "path": "/ratgeber/rapido-wohnmobil-verkaufen",
    "h1": "Rapido Wohnmobil verkaufen",
    "metaDescription": "Rapido Wohnmobil verkaufen zum Top-Preis. Ob Distinction, Serie 8 oder Serie 6 — erfahren Sie, wie Sie den maximalen Erlös für Ihr Premium-Reisemobil erzielen.",
    "category": "brand",
    "brandName": "Rapido",
    "dataFile": "ratgeber-rapido"
  },
  {
    "slug": "rapido-wohnmobil-versteigern",
    "path": "/ratgeber/rapido-wohnmobil-versteigern",
    "h1": "Rapido Wohnmobil versteigern",
    "metaDescription": "Rapido Wohnmobil versteigern und durch Bieterwettbewerb den Premium-Preis erzielen. Sicher mit Mindestgebot bei CaravanWert.",
    "category": "brand",
    "brandName": "Rapido",
    "dataFile": "ratgeber-rapido"
  },
  {
    "slug": "rapido-wohnmobil-wert-ermitteln",
    "path": "/ratgeber/rapido-wohnmobil-wert-ermitteln",
    "h1": "Wert Ihres Rapido Wohnmobils ermitteln",
    "metaDescription": "Ermitteln Sie den aktuellen Marktwert Ihres Rapido Wohnmobils. Premium-Bewertung für Distinction, Serie 8, Serie 6 und V-Serie — kostenlos in 24 Stunden.",
    "category": "brand",
    "brandName": "Rapido",
    "dataFile": "ratgeber-rapido"
  },
  {
    "slug": "sunlight-wohnmobil-verkaufen",
    "path": "/ratgeber/sunlight-wohnmobil-verkaufen",
    "h1": "Sunlight Wohnmobil verkaufen",
    "metaDescription": "Sunlight Wohnmobil verkaufen zum Bestpreis. Ob T-Serie, I-Serie oder Cliff — erfahren Sie, wie Sie den maximalen Erlös erzielen.",
    "category": "brand",
    "brandName": "Sunlight",
    "dataFile": "ratgeber-sunlight"
  },
  {
    "slug": "sunlight-wohnmobil-versteigern",
    "path": "/ratgeber/sunlight-wohnmobil-versteigern",
    "h1": "Sunlight Wohnmobil versteigern",
    "metaDescription": "Sunlight Wohnmobil versteigern und durch Bieterwettbewerb den besten Preis erzielen. Sicher mit Mindestgebot bei CaravanWert.",
    "category": "brand",
    "brandName": "Sunlight",
    "dataFile": "ratgeber-sunlight"
  },
  {
    "slug": "sunlight-wohnmobil-wert-ermitteln",
    "path": "/ratgeber/sunlight-wohnmobil-wert-ermitteln",
    "h1": "Wert Ihres Sunlight Wohnmobils ermitteln",
    "metaDescription": "Ermitteln Sie den aktuellen Marktwert Ihres Sunlight Wohnmobils. Bewertung für T-Serie, I-Serie, Cliff und A-Serie — kostenlos in 24 Stunden.",
    "category": "brand",
    "brandName": "Sunlight",
    "dataFile": "ratgeber-sunlight"
  },
  {
    "slug": "was-kostet-mein-adria-wohnmobil",
    "path": "/ratgeber/was-kostet-mein-adria-wohnmobil",
    "h1": "Was kostet mein Adria Wohnmobil?",
    "metaDescription": "Aktuelle Marktpreise für Adria Wohnmobile. Preisübersicht für Coral, Matrix, Twin und Sonic. Kostenlose Wertermittlung.",
    "category": "brand",
    "brandName": "Adria",
    "dataFile": "ratgeber-adria"
  },
  {
    "slug": "was-kostet-mein-buerstner-wohnmobil",
    "path": "/ratgeber/was-kostet-mein-buerstner-wohnmobil",
    "h1": "Was kostet mein Bürstner Wohnmobil?",
    "metaDescription": "Aktuelle Marktpreise für Bürstner Wohnmobile. Preisübersicht für Lyseo, Ixeo, Elegance und Campeo. Kostenlose Wertermittlung.",
    "category": "brand",
    "brandName": "Bürstner",
    "dataFile": "ratgeber-buerstner"
  },
  {
    "slug": "was-kostet-mein-carado-wohnmobil",
    "path": "/ratgeber/was-kostet-mein-carado-wohnmobil",
    "h1": "Was kostet mein Carado Wohnmobil?",
    "metaDescription": "Aktuelle Gebrauchtpreise für Carado Wohnmobile. Preisübersicht für T-Modelle, I-Modelle, Vlow und A-Modelle.",
    "category": "brand",
    "brandName": "Carado",
    "dataFile": "ratgeber-carado"
  },
  {
    "slug": "was-kostet-mein-carthago-wohnmobil",
    "path": "/ratgeber/was-kostet-mein-carthago-wohnmobil",
    "h1": "Was kostet mein Carthago Wohnmobil?",
    "metaDescription": "Aktuelle Marktpreise für Carthago Wohnmobile. Preisübersicht für Chic C-Line, E-Line, C-Tourer und Liner. Kostenlose Wertermittlung.",
    "category": "brand",
    "brandName": "Carthago",
    "dataFile": "ratgeber-carthago"
  },
  {
    "slug": "was-kostet-mein-chausson-wohnmobil",
    "path": "/ratgeber/was-kostet-mein-chausson-wohnmobil",
    "h1": "Was kostet mein Chausson Wohnmobil?",
    "metaDescription": "Aktuelle Gebrauchtpreise für Chausson Wohnmobile. Preisübersicht für Titanium, Welcome, Flash und X-Campingbus.",
    "category": "brand",
    "brandName": "Chausson",
    "dataFile": "ratgeber-chausson"
  },
  {
    "slug": "was-kostet-mein-concorde-wohnmobil",
    "path": "/ratgeber/was-kostet-mein-concorde-wohnmobil",
    "h1": "Was kostet mein Concorde Wohnmobil?",
    "metaDescription": "Aktuelle Gebrauchtpreise für Concorde Wohnmobile. Preisübersicht für Liner, Carver, Charisma und Credo — Deutschlands exklusivste Reisemobile.",
    "category": "brand",
    "brandName": "Concorde",
    "dataFile": "ratgeber-concorde"
  },
  {
    "slug": "was-kostet-mein-dethleffs-wohnmobil",
    "path": "/ratgeber/was-kostet-mein-dethleffs-wohnmobil",
    "h1": "Was kostet mein Dethleffs Wohnmobil?",
    "metaDescription": "Aktuelle Marktpreise für Dethleffs Wohnmobile. Preisübersicht für Globebus, Esprit, Pulse und Alpa. Kostenlose Wertermittlung mit Echtzeitdaten.",
    "category": "brand",
    "brandName": "Dethleffs",
    "dataFile": "ratgeber-dethleffs"
  },
  {
    "slug": "was-kostet-mein-hobby-wohnmobil",
    "path": "/ratgeber/was-kostet-mein-hobby-wohnmobil",
    "h1": "Was kostet mein Hobby Wohnmobil?",
    "metaDescription": "Aktuelle Gebrauchtpreise für Hobby Wohnmobile. Preisübersicht für Optima, Siesta, Vantana und De Luxe. Kostenlose Wertermittlung.",
    "category": "brand",
    "brandName": "Hobby",
    "dataFile": "ratgeber-hobby"
  },
  {
    "slug": "was-kostet-mein-hymer-wohnmobil",
    "path": "/ratgeber/was-kostet-mein-hymer-wohnmobil",
    "h1": "Was kostet mein Hymer Wohnmobil?",
    "metaDescription": "Was ist Ihr Hymer Wohnmobil wert? Aktuelle Marktpreise für B-Klasse, Exsis, ML-T und Grand Canyon. Kostenlose Bewertung mit Echtzeit-Marktdaten.",
    "category": "brand",
    "brandName": "Hymer",
    "dataFile": "ratgeber-hymer"
  },
  {
    "slug": "was-kostet-mein-knaus-wohnmobil",
    "path": "/ratgeber/was-kostet-mein-knaus-wohnmobil",
    "h1": "Was kostet mein Knaus Wohnmobil?",
    "metaDescription": "Aktuelle Marktpreise für Knaus Wohnmobile. Preisübersicht für Sun TI, Sky Wave, Van TI und BoxStar. Kostenlose Wertermittlung.",
    "category": "brand",
    "brandName": "Knaus",
    "dataFile": "ratgeber-knaus"
  },
  {
    "slug": "was-kostet-mein-laika-wohnmobil",
    "path": "/ratgeber/was-kostet-mein-laika-wohnmobil",
    "h1": "Was kostet mein Laika Wohnmobil?",
    "metaDescription": "Aktuelle Gebrauchtpreise für Laika Wohnmobile. Preisübersicht für Ecovip, Kreos, Kosmo und Ecovip H — datenbasiert und kostenlos.",
    "category": "brand",
    "brandName": "Laika",
    "dataFile": "ratgeber-laika"
  },
  {
    "slug": "was-kostet-mein-poessl-wohnmobil",
    "path": "/ratgeber/was-kostet-mein-poessl-wohnmobil",
    "h1": "Was kostet mein Pössl Wohnmobil?",
    "metaDescription": "Aktuelle Gebrauchtpreise für Pössl Kastenwagen. Preisübersicht für Summit, Roadcamp, Campster und Vanster.",
    "category": "brand",
    "brandName": "Pössl",
    "dataFile": "ratgeber-poessl"
  },
  {
    "slug": "was-kostet-mein-rapido-wohnmobil",
    "path": "/ratgeber/was-kostet-mein-rapido-wohnmobil",
    "h1": "Was kostet mein Rapido Wohnmobil?",
    "metaDescription": "Aktuelle Gebrauchtpreise für Rapido Wohnmobile. Preisübersicht für Distinction, Serie 8, Serie 6 und V-Serie.",
    "category": "brand",
    "brandName": "Rapido",
    "dataFile": "ratgeber-rapido"
  },
  {
    "slug": "was-kostet-mein-sunlight-wohnmobil",
    "path": "/ratgeber/was-kostet-mein-sunlight-wohnmobil",
    "h1": "Was kostet mein Sunlight Wohnmobil?",
    "metaDescription": "Aktuelle Gebrauchtpreise für Sunlight Wohnmobile. Preisübersicht für T-Serie, I-Serie, Cliff und A-Serie.",
    "category": "brand",
    "brandName": "Sunlight",
    "dataFile": "ratgeber-sunlight"
  },
  {
    "slug": "was-kostet-mein-weinsberg-wohnmobil",
    "path": "/ratgeber/was-kostet-mein-weinsberg-wohnmobil",
    "h1": "Was kostet mein Weinsberg Wohnmobil?",
    "metaDescription": "Aktuelle Gebrauchtpreise für Weinsberg Wohnmobile. Preisübersicht für CaraCompact, CaraBus, CaraSuite und CaraHome.",
    "category": "brand",
    "brandName": "Weinsberg",
    "dataFile": "ratgeber-weinsberg"
  },
  {
    "slug": "weinsberg-wohnmobil-verkaufen",
    "path": "/ratgeber/weinsberg-wohnmobil-verkaufen",
    "h1": "Weinsberg Wohnmobil verkaufen",
    "metaDescription": "Weinsberg Wohnmobil verkaufen zum Top-Preis. Ob CaraCompact, CaraSuite oder CaraBus — erfahren Sie, wie Sie den maximalen Erlös erzielen.",
    "category": "brand",
    "brandName": "Weinsberg",
    "dataFile": "ratgeber-weinsberg"
  },
  {
    "slug": "weinsberg-wohnmobil-versteigern",
    "path": "/ratgeber/weinsberg-wohnmobil-versteigern",
    "h1": "Weinsberg Wohnmobil versteigern",
    "metaDescription": "Weinsberg Wohnmobil versteigern und durch Bieterwettbewerb den besten Preis erzielen. Sicher mit Mindestgebot bei CaravanWert.",
    "category": "brand",
    "brandName": "Weinsberg",
    "dataFile": "ratgeber-weinsberg"
  },
  {
    "slug": "weinsberg-wohnmobil-wert-ermitteln",
    "path": "/ratgeber/weinsberg-wohnmobil-wert-ermitteln",
    "h1": "Wert Ihres Weinsberg Wohnmobils ermitteln",
    "metaDescription": "Ermitteln Sie den aktuellen Marktwert Ihres Weinsberg Wohnmobils. Bewertung für CaraCompact, CaraBus, CaraSuite und CaraHome — kostenlos.",
    "category": "brand",
    "brandName": "Weinsberg",
    "dataFile": "ratgeber-weinsberg"
  },
  {
    "slug": "wie-verkaufe-ich-mein-adria-wohnmobil",
    "path": "/ratgeber/wie-verkaufe-ich-mein-adria-wohnmobil",
    "h1": "Wie verkaufe ich mein Adria Wohnmobil?",
    "metaDescription": "Schritt-für-Schritt zum Adria-Verkauf. Vorbereitung, Preisfindung, Verkaufskanal und Übergabe — komplett erklärt.",
    "category": "brand",
    "brandName": "Adria",
    "dataFile": "ratgeber-adria"
  },
  {
    "slug": "wie-verkaufe-ich-mein-buerstner-wohnmobil",
    "path": "/ratgeber/wie-verkaufe-ich-mein-buerstner-wohnmobil",
    "h1": "Wie verkaufe ich mein Bürstner Wohnmobil?",
    "metaDescription": "Schritt-für-Schritt zum Bürstner-Verkauf. Vorbereitung, Preisfindung, Verkaufsweg und sichere Übergabe — komplett erklärt.",
    "category": "brand",
    "brandName": "Bürstner",
    "dataFile": "ratgeber-buerstner"
  },
  {
    "slug": "wie-verkaufe-ich-mein-carado-wohnmobil",
    "path": "/ratgeber/wie-verkaufe-ich-mein-carado-wohnmobil",
    "h1": "Wie verkaufe ich mein Carado Wohnmobil?",
    "metaDescription": "Schritt-für-Schritt zum Carado-Verkauf. Vorbereitung, Preisfindung, Verkaufskanal und Übergabe — komplett erklärt.",
    "category": "brand",
    "brandName": "Carado",
    "dataFile": "ratgeber-carado"
  },
  {
    "slug": "wie-verkaufe-ich-mein-carthago-wohnmobil",
    "path": "/ratgeber/wie-verkaufe-ich-mein-carthago-wohnmobil",
    "h1": "Wie verkaufe ich mein Carthago Wohnmobil?",
    "metaDescription": "Schritt-für-Schritt zum Carthago-Verkauf. Premium-Vorbereitung, Preisfindung und sichere Abwicklung für Ihre Premiumklasse.",
    "category": "brand",
    "brandName": "Carthago",
    "dataFile": "ratgeber-carthago"
  },
  {
    "slug": "wie-verkaufe-ich-mein-chausson-wohnmobil",
    "path": "/ratgeber/wie-verkaufe-ich-mein-chausson-wohnmobil",
    "h1": "Wie verkaufe ich mein Chausson Wohnmobil?",
    "metaDescription": "Schritt-für-Schritt zum Chausson-Verkauf. Vorbereitung, Preisfindung und Übergabe — mit Ford-Basis-Tipps.",
    "category": "brand",
    "brandName": "Chausson",
    "dataFile": "ratgeber-chausson"
  },
  {
    "slug": "wie-verkaufe-ich-mein-concorde-wohnmobil",
    "path": "/ratgeber/wie-verkaufe-ich-mein-concorde-wohnmobil",
    "h1": "Wie verkaufe ich mein Concorde Wohnmobil?",
    "metaDescription": "Schritt-für-Schritt zum Concorde-Verkauf. Luxus-spezifische Strategien für diskrete Abwicklung und maximalen Erlös.",
    "category": "brand",
    "brandName": "Concorde",
    "dataFile": "ratgeber-concorde"
  },
  {
    "slug": "wie-verkaufe-ich-mein-dethleffs-wohnmobil",
    "path": "/ratgeber/wie-verkaufe-ich-mein-dethleffs-wohnmobil",
    "h1": "Wie verkaufe ich mein Dethleffs Wohnmobil?",
    "metaDescription": "Schritt-für-Schritt zum Dethleffs-Verkauf. Vorbereitung, Preisfindung, Verkaufsweg und sichere Übergabe — alles was Sie wissen müssen.",
    "category": "brand",
    "brandName": "Dethleffs",
    "dataFile": "ratgeber-dethleffs"
  },
  {
    "slug": "wie-verkaufe-ich-mein-hobby-wohnmobil",
    "path": "/ratgeber/wie-verkaufe-ich-mein-hobby-wohnmobil",
    "h1": "Wie verkaufe ich mein Hobby Wohnmobil?",
    "metaDescription": "Schritt-für-Schritt zum Hobby-Verkauf. Vorbereitung, Preisfindung, Verkaufskanal und Übergabe — komplett erklärt.",
    "category": "brand",
    "brandName": "Hobby",
    "dataFile": "ratgeber-hobby"
  },
  {
    "slug": "wie-verkaufe-ich-mein-hymer-wohnmobil",
    "path": "/ratgeber/wie-verkaufe-ich-mein-hymer-wohnmobil",
    "h1": "Wie verkaufe ich mein Hymer Wohnmobil?",
    "metaDescription": "Schritt-für-Schritt-Anleitung zum Verkauf Ihres Hymer Wohnmobils. Von der Vorbereitung bis zur Übergabe — so erzielen Sie den besten Preis.",
    "category": "brand",
    "brandName": "Hymer",
    "dataFile": "ratgeber-hymer"
  },
  {
    "slug": "wie-verkaufe-ich-mein-knaus-wohnmobil",
    "path": "/ratgeber/wie-verkaufe-ich-mein-knaus-wohnmobil",
    "h1": "Wie verkaufe ich mein Knaus Wohnmobil?",
    "metaDescription": "Schritt-für-Schritt zum Knaus-Verkauf. Von der Vorbereitung bis zur sicheren Übergabe — so erzielen Sie den besten Preis für Ihren Knaus.",
    "category": "brand",
    "brandName": "Knaus",
    "dataFile": "ratgeber-knaus"
  },
  {
    "slug": "wie-verkaufe-ich-mein-laika-wohnmobil",
    "path": "/ratgeber/wie-verkaufe-ich-mein-laika-wohnmobil",
    "h1": "Wie verkaufe ich mein Laika Wohnmobil?",
    "metaDescription": "Schritt-für-Schritt zum Laika-Verkauf. Vorbereitung, Preisfindung und Übergabe — mit Tipps für italienische Reisemobile.",
    "category": "brand",
    "brandName": "Laika",
    "dataFile": "ratgeber-laika"
  },
  {
    "slug": "wie-verkaufe-ich-mein-poessl-wohnmobil",
    "path": "/ratgeber/wie-verkaufe-ich-mein-poessl-wohnmobil",
    "h1": "Wie verkaufe ich mein Pössl Wohnmobil?",
    "metaDescription": "Schritt-für-Schritt zum Pössl-Verkauf. Kastenwagen-spezifische Tipps für Vorbereitung, Preisfindung und Übergabe.",
    "category": "brand",
    "brandName": "Pössl",
    "dataFile": "ratgeber-poessl"
  },
  {
    "slug": "wie-verkaufe-ich-mein-rapido-wohnmobil",
    "path": "/ratgeber/wie-verkaufe-ich-mein-rapido-wohnmobil",
    "h1": "Wie verkaufe ich mein Rapido Wohnmobil?",
    "metaDescription": "Schritt-für-Schritt zum Rapido-Verkauf. Premium-spezifische Tipps für Vorbereitung, Preisfindung und diskrete Abwicklung.",
    "category": "brand",
    "brandName": "Rapido",
    "dataFile": "ratgeber-rapido"
  },
  {
    "slug": "wie-verkaufe-ich-mein-sunlight-wohnmobil",
    "path": "/ratgeber/wie-verkaufe-ich-mein-sunlight-wohnmobil",
    "h1": "Wie verkaufe ich mein Sunlight Wohnmobil?",
    "metaDescription": "Schritt-für-Schritt zum Sunlight-Verkauf. Vorbereitung, Preisfindung, Verkaufskanal und Übergabe — komplett erklärt.",
    "category": "brand",
    "brandName": "Sunlight",
    "dataFile": "ratgeber-sunlight"
  },
  {
    "slug": "wie-verkaufe-ich-mein-weinsberg-wohnmobil",
    "path": "/ratgeber/wie-verkaufe-ich-mein-weinsberg-wohnmobil",
    "h1": "Wie verkaufe ich mein Weinsberg Wohnmobil?",
    "metaDescription": "Schritt-für-Schritt zum Weinsberg-Verkauf. Vorbereitung, Preisfindung, Verkaufskanal und Übergabe — komplett erklärt.",
    "category": "brand",
    "brandName": "Weinsberg",
    "dataFile": "ratgeber-weinsberg"
  },
  {
    "slug": "wohnmobil-bei-scheidung-verkaufen",
    "path": "/ratgeber/wohnmobil-bei-scheidung-verkaufen",
    "h1": "Wohnmobil bei Scheidung verkaufen",
    "metaDescription": "Wohnmobil bei Scheidung verkaufen? Erfahren Sie, wie die Vermögensaufteilung funktioniert und wie Sie das Fahrzeug schnell und fair verwerten.",
    "category": "condition",
    "dataFile": "ratgeber-condition-situation"
  },
  {
    "slug": "wohnmobil-im-erbfall-verkaufen",
    "path": "/ratgeber/wohnmobil-im-erbfall-verkaufen",
    "h1": "Wohnmobil im Erbfall verkaufen",
    "metaDescription": "Wohnmobil geerbt und möchten verkaufen? Erfahren Sie, welche Schritte nötig sind, welche Unterlagen Sie brauchen und wie Sie den besten Preis erzielen.",
    "category": "condition",
    "dataFile": "ratgeber-condition-situation"
  },
  {
    "slug": "wohnmobil-mit-getriebeschaden-verkaufen",
    "path": "/ratgeber/wohnmobil-mit-getriebeschaden-verkaufen",
    "h1": "Wohnmobil mit Getriebeschaden verkaufen",
    "metaDescription": "Wohnmobil mit Getriebeschaden verkaufen? Erfahren Sie, welchen Restwert Ihr Wohnmobil trotz Getriebedefekt noch hat und wie der Verkauf funktioniert.",
    "category": "condition",
    "dataFile": "ratgeber-condition-damage"
  },
  {
    "slug": "wohnmobil-mit-hagelschaden-verkaufen",
    "path": "/ratgeber/wohnmobil-mit-hagelschaden-verkaufen",
    "h1": "Wohnmobil mit Hagelschaden verkaufen",
    "metaDescription": "Wohnmobil mit Hagelschaden verkaufen? Erfahren Sie, wie viel Ihr Wohnmobil trotz Hageldellen wert ist und wann sich die Reparatur lohnt.",
    "category": "condition",
    "dataFile": "ratgeber-condition-damage"
  },
  {
    "slug": "wohnmobil-mit-hoher-laufleistung-verkaufen",
    "path": "/ratgeber/wohnmobil-mit-hoher-laufleistung-verkaufen",
    "h1": "Wohnmobil mit hoher Laufleistung verkaufen",
    "metaDescription": "Wohnmobil mit hoher Laufleistung verkaufen? Erfahren Sie, ab wann Kilometer kritisch werden und wie Sie trotzdem einen guten Preis erzielen.",
    "category": "condition",
    "dataFile": "ratgeber-condition-situation"
  },
  {
    "slug": "wohnmobil-mit-leasingvertrag-verkaufen",
    "path": "/ratgeber/wohnmobil-mit-leasingvertrag-verkaufen",
    "h1": "Wohnmobil mit Leasingvertrag verkaufen",
    "metaDescription": "Wohnmobil mit Leasingvertrag verkaufen? Erfahren Sie Ihre Optionen bei vorzeitiger Beendigung, Übernahme und Ablösung des Leasingvertrags.",
    "category": "condition",
    "dataFile": "ratgeber-condition-situation"
  },
  {
    "slug": "wohnmobil-mit-motorschaden-verkaufen",
    "path": "/ratgeber/wohnmobil-mit-motorschaden-verkaufen",
    "h1": "Wohnmobil mit Motorschaden verkaufen",
    "metaDescription": "Wohnmobil mit Motorschaden verkaufen? Erfahren Sie, welchen Preis Sie trotz Motordefekt erzielen und wie der Verkauf unkompliziert gelingt.",
    "category": "condition",
    "dataFile": "ratgeber-condition-damage"
  },
  {
    "slug": "wohnmobil-mit-reparaturstau-verkaufen",
    "path": "/ratgeber/wohnmobil-mit-reparaturstau-verkaufen",
    "h1": "Wohnmobil mit Reparaturstau verkaufen",
    "metaDescription": "Wohnmobil mit Reparaturstau verkaufen? Erfahren Sie, wie viel Ihr Wohnmobil trotz aufgestauter Reparaturen noch wert ist und wie der Verkauf funktioniert.",
    "category": "condition",
    "dataFile": "ratgeber-condition-situation"
  },
  {
    "slug": "wohnmobil-mit-schimmel-verkaufen",
    "path": "/ratgeber/wohnmobil-mit-schimmel-verkaufen",
    "h1": "Wohnmobil mit Schimmel verkaufen",
    "metaDescription": "Wohnmobil mit Schimmel verkaufen? Erfahren Sie, wie viel Ihr Wohnmobil trotz Schimmelbefall wert ist und welche Optionen Sie haben.",
    "category": "condition",
    "dataFile": "ratgeber-condition-damage"
  },
  {
    "slug": "wohnmobil-mit-unfallschaden-verkaufen",
    "path": "/ratgeber/wohnmobil-mit-unfallschaden-verkaufen",
    "h1": "Wohnmobil mit Unfallschaden verkaufen",
    "metaDescription": "Wohnmobil mit Unfallschaden verkaufen? Erfahren Sie, wie viel Ihr Unfallwohnmobil noch wert ist und wie Sie es schnell und fair verkaufen.",
    "category": "condition",
    "dataFile": "ratgeber-condition-damage"
  },
  {
    "slug": "wohnmobil-mit-wasserschaden-verkaufen",
    "path": "/ratgeber/wohnmobil-mit-wasserschaden-verkaufen",
    "h1": "Wohnmobil mit Wasserschaden verkaufen",
    "metaDescription": "Wohnmobil mit Wasserschaden verkaufen? Erfahren Sie, wie viel Ihr Wohnmobil trotz Feuchtigkeit noch wert ist und wie Sie es stressfrei verkaufen.",
    "category": "condition",
    "dataFile": "ratgeber-condition-damage"
  },
  {
    "slug": "wohnmobil-ohne-tuev-verkaufen",
    "path": "/ratgeber/wohnmobil-ohne-tuev-verkaufen",
    "h1": "Wohnmobil ohne TÜV verkaufen",
    "metaDescription": "Wohnmobil ohne TÜV verkaufen? Erfahren Sie, wie viel Ihr Wohnmobil trotz abgelaufener HU noch wert ist und wie der Verkauf legal funktioniert.",
    "category": "condition",
    "dataFile": "ratgeber-condition-situation"
  },
  {
    "slug": "wohnmobil-trotz-finanzierung-verkaufen",
    "path": "/ratgeber/wohnmobil-trotz-finanzierung-verkaufen",
    "h1": "Wohnmobil trotz Finanzierung verkaufen",
    "metaDescription": "Wohnmobil trotz laufender Finanzierung verkaufen? Erfahren Sie, wie die Restschuldablösung funktioniert und was Sie beachten müssen.",
    "category": "condition",
    "dataFile": "ratgeber-condition-situation"
  }
];
