-- ============================================================================
-- Migration: Blank Handover Protocol (PDF zum Ausdrucken & Mitnehmen)
-- Date: 2026-04-22
-- Description:
--   1. Adds `blank_protocol_url` + `blank_protocol_storage_path` columns to
--      `purchase_contracts` to track the PRE-FILLED handover-protocol PDF that
--      is generated together with the Kaufvertrag and sent in a SEPARATE
--      e-mail to seller + buyer (so they can print it out and use it on the
--      handover day).
--   2. Creates a private `handover-protocols` storage bucket with the same
--      RLS pattern as `purchase-contracts` (admin / service-role / owner-read).
--
-- IMPORTANT distinction:
--   - `appointments.handover_protocol_url`     → completed protocol AFTER handover
--                                                (HTML, generated by `generate-handover-pdf`)
--   - `purchase_contracts.blank_protocol_url`  → BLANK protocol BEFORE handover
--                                                (PDF, generated by `generate-blank-handover-protocol`)
-- ============================================================================

-- ─── 1. New columns on purchase_contracts ────────────────────────────────────
ALTER TABLE public.purchase_contracts
  ADD COLUMN IF NOT EXISTS blank_protocol_url TEXT;

ALTER TABLE public.purchase_contracts
  ADD COLUMN IF NOT EXISTS blank_protocol_storage_path TEXT;

COMMENT ON COLUMN public.purchase_contracts.blank_protocol_url IS
  'Signed URL to the BLANK handover-protocol PDF (vor der Übergabe per E-Mail verschickt, zum Ausdrucken).';
COMMENT ON COLUMN public.purchase_contracts.blank_protocol_storage_path IS
  'Storage path in handover-protocols bucket (z. B. {sellerId}/KV-2026-00001_uebergabeprotokoll.pdf).';

-- ─── 2. Storage bucket ───────────────────────────────────────────────────────
INSERT INTO storage.buckets (id, name, public)
VALUES ('handover-protocols', 'handover-protocols', false)
ON CONFLICT (id) DO NOTHING;

-- ─── 3. Storage RLS policies (idempotent) ────────────────────────────────────
DROP POLICY IF EXISTS "Admin full access to handover-protocols" ON storage.objects;
CREATE POLICY "Admin full access to handover-protocols"
  ON storage.objects FOR ALL
  USING (
    bucket_id = 'handover-protocols' AND EXISTS (
      SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin'
    )
  )
  WITH CHECK (
    bucket_id = 'handover-protocols' AND EXISTS (
      SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin'
    )
  );

DROP POLICY IF EXISTS "Service role full access to handover-protocols" ON storage.objects;
CREATE POLICY "Service role full access to handover-protocols"
  ON storage.objects FOR ALL
  USING (bucket_id = 'handover-protocols')
  WITH CHECK (bucket_id = 'handover-protocols');

DROP POLICY IF EXISTS "Users can read own handover-protocols" ON storage.objects;
CREATE POLICY "Users can read own handover-protocols"
  ON storage.objects FOR SELECT
  USING (
    bucket_id = 'handover-protocols'
    AND auth.uid()::text = (storage.foldername(name))[1]
  );
